import {glossaryEnglish} from './glossary-english.js';
import {englishLessons,englishGroups} from './lesson-english.js';
export const refs = {
 isa:'https://docs.riscv.org/reference/isa/v20240411/unpriv/rv32.html',
 rv64:'https://docs.riscv.org/reference/isa/v20240411/unpriv/rv64.html',
 abi:'https://riscv-non-isa.github.io/riscv-elf-psabi-doc/',
 assembly:'https://github.com/riscv-non-isa/riscv-asm-manual/blob/main/src/asm-manual.adoc',
 textbook:'https://shop.elsevier.com/books/book-companion/9780128203316',
 multiply:'https://docs.riscv.org/reference/isa/v20240411/unpriv/m-st-ext.html'
};
const s=(title,body,extra={})=>({title,body,...extra});
export const groups=[{id:'lect1',label:'Lecture 01',title:'الصورة الكبيرة',desc:'من البرنامج إلى المكوّنات التي تنفّذه.',file:'Lect1_v3.pdf'}, {id:'lab1',label:'Lab 01',title:'من الـLogic إلى الـAssembly',desc:'بوابات، دوائر، وأول برنامج RISC-V.',file:'Lab01.pdf'}, {id:'lect2',label:'Lecture 02',title:'الأداء ولغة الكمبيوتر',desc:'احسب السرعة، وافهم الـRegisters والـMemory.',file:'Lect2.pdf'}, {id:'lab2',label:'Lab 02',title:'طبّق اللي فهمته',desc:'Instruction formats وحلول اللابات خطوة بخطوة.',file:'Lab02.pdf'}];
export const lessons=[
{id:'abstraction',group:'lect1',title:'من الكود إلى الـHardware',english:'Abstraction & Architecture',minutes:7,source:'Lect1_v3.pdf · pp. 2–8',summary:'كل مستوى يخفي تفاصيل المستوى اللي تحته، لكن فهم العلاقة بينهم هو بداية فهم الكمبيوتر.',sections:[
s('ليه ندرس Computer Architecture؟','ممكن تكتب برنامج صحيح لكنه بطيء جدًا. عشان تفهم السبب، محتاج تعرف المعالج بيقرأ البيانات إزاي، وبينفّذ كام Instruction، وبيرجع للـMemory قد إيه. المادة بتربط Software بـHardware؛ الهدف هنا إنك تقدر تتبع برنامج صغير وتحسب تكلفته.'),
s('Levels of Abstraction','تخيّل سلم: Application ثم Operating System ثم Instructions وRegisters ثم Datapath وControl ثم Logic Gates ثم Transistors. كل طبقة بتتعامل مع واجهة واضحة بدل ما تعيد فهم الإلكترونيات كلها. الـOS يدير موارد مثل الذاكرة والأجهزة، والـApplication يستخدم الخدمات دي.',{list:['Application: المهمة اللي المستخدم عايزها.','Operating System: إدارة Memory وI/O والعمليات.','ISA: التعليمات والـRegisters اللي البرنامج يقدر يستخدمها.','Microarchitecture: الدوائر وطريقة تنفيذ الـISA.','Digital Logic: Gates، Adders، Flip-Flops.']}),
s('Architecture vs. Microarchitecture','الـArchitecture هي الواجهة اللي المبرمج شايفها: تعليمات، Registers، وسلوك الوصول للذاكرة. الـMicroarchitecture هي طريقة تنفيذ الواجهة في Hardware. معالج بسيط ومعالج فيه Pipeline ممكن ينفّذوا نفس ISA، لكن عدد الـCycles والأداء مختلفين.',{table:{heads:['وجه المقارنة','Architecture / ISA','Microarchitecture'],rows:[['السؤال','البرنامج يقدر يعمل إيه؟','الهاردوير ينفّذه إزاي؟'],['مثال','add و32 Register','ALU وControl وPipeline'],['الأثر','توافق البرامج والتعليمات','السرعة والطاقة والتكلفة']]}}),
s('الفكرة في مثال واحد','تعليمة add x5, x6, x7 معناها جمع قيمتين ووضع الناتج في x5. المعنى ده جزء من الـISA. هل التعليمة تأخذ Cycle واحدة أو عدة Cycles؟ وهل تبدأ تعليمة بعدها قبل ما تخلص؟ دي قرارات Microarchitecture. نفس المعنى لا يضمن نفس السرعة.',{code:'add x5, x6, x7   # x5 = x6 + x7'}),
s('خريطة المذاكرة','ابدأ بالمكوّنات، بعدين Digital Logic، بعدين Performance، وبعدها RISC-V. الـPipelining وVerilog والـMemory Systems مذكورين كأهداف مستقبلية للمقرر، لكن تفاصيلهم خارج الملفات الأربعة المتاحة هنا.')],takeaway:'ISA تحدد السلوك؛ Microarchitecture تحدد التنفيذ.'},
{id:'von-neumann',group:'lect1',title:'الكمبيوتر كمنظومة واحدة',english:'Von Neumann Model',minutes:6,source:'Lect1_v3.pdf · pp. 9–12, 31',summary:'برنامج وبيانات في Memory، ومعالج يقرأ وينفّذ ويتواصل مع العالم.',visual:'system',sections:[
s('من التوصيلات إلى Stored Program','في الأنظمة المبكرة كان تغيير المهمة ممكن يتطلب تغيير توصيلات وإعدادات. فكرة Stored-program خلّت البرنامج نفسه بيانات مخزنة يمكن قراءتها. ده فصل المهمة عن إعادة بناء الدائرة لكل مسألة.'),
s('المكوّنات الخمسة','نموذج Von Neumann يضم Memory وProcessing Unit وControl Unit وInput وOutput. الـALU جزء المعالجة الحسابية والمنطقية، والـCU تنسق العمل. في الكمبيوتر الحديث بنجمع الـALU والـCU والـRegisters داخل CPU.',{list:['Memory: تخزّن التعليمات والبيانات.','ALU: تحسب وتنفّذ العمليات المنطقية.','Control Unit: تحدد توقيت ومسار التنفيذ.','Input: بيانات داخلة، مثل Keyboard.','Output: نتائج خارجة، مثل Monitor.']}),
s('يعني إيه نفس الذاكرة؟','في النموذج الكلاسيكي، التعليمات والبيانات يشتركوا في Memory. المعالج محتاج يتبادل الاتنين عبر مسارات اتصال؛ ده يساعد في فهم Von Neumann bottleneck. المعالجات الحديثة قد تفصل Instruction Cache عن Data Cache داخليًا، لذلك النموذج مدخل تعليمي وليس وصفًا حرفيًا لكل تفاصيل كل معالج.'),
s('I/O من وجهة نظر الـCPU','في Memory-mapped I/O بعض العناوين تشير لأجهزة بدل RAM. القراءة أو الكتابة للعنوان ده تتعامل مع Device Register. في Instruction-based I/O توجد تعليمات خاصة بالـI/O في بعض الـISAs. Touch screen وNetwork card ممكن يكونوا Input وOutput معًا.'),
s('تتبّع طلب بسيط','لو هتجمع رقمين: Input يدخل القيم، Memory يحتفظ بها وبالبرنامج، CU تجلب التعليمات، Registers تمسك القيم المطلوبة، ALU تجمع، ثم يُحفظ أو يُعرض الناتج. المكوّنات متعاونة؛ الـMemory لا تحسب، والـALU لا تقرر وحدها أي تعليمة تأتي بعد ذلك.')],takeaway:'Stored Program يعني إن تعليمات البرنامج قابلة للتخزين والقراءة مثل البيانات.'},
{id:'memory-buses',group:'lect1',title:'عنوان، قيمة، وإشارة تحكم',english:'Buses & Memory Organization',minutes:8,source:'Lect1_v3.pdf · pp. 20–26',summary:'فرّق بين مكان البيانات والبيانات نفسها، واعرف سعة الذاكرة من عدد خطوط العنوان.',visual:'address',sections:[
s('أنواع الـBus','الـBus مسار اتصال بين أجزاء النظام. Data Bus ينقل القيمة، Address Bus يحدد المكان، وControl Bus ينقل إشارات مثل Read وWrite. عرض Data Bus لا يساوي تلقائيًا عرض Address Bus.',{table:{heads:['Bus','وظيفته','مثال'],rows:[['Address','تحديد المكان','العنوان 4096'],['Data','نقل المحتوى','القيمة 27'],['Control','تحديد العملية والتوقيت','Read أو Write']]}}),
s('حساب عدد المواقع','لو عندك n Address bits، فيه 2^n عنوان ممكن. السعة الكلية تعتمد على حجم كل موقع: Capacity = 2^n × bits per location. في Byte-addressed memory كل عنوان يحدد Byte واحدة؛ Address Bus من 16 bit يتيح 65,536 Byte = 64 KiB.',{formula:'Locations = 2ⁿ     Capacity (bits) = Locations × m'}),
s('شكل k × m','شريحة 4M × 16-bit فيها 4M موقع، كل موقع 16 bit. لو M = 2^20: السعة = 2^22 × 16 bit = 2^26 bit = 8 MiB، وتحتاج 22 Address bits لتحديد المواقع. لازم تميّز بين تسمية شريحة ذات مواقع 16 bit ونظام RISC-V اللي عناوين ذاكرته Byte-addressed.'),
s('MAR وMDR','MAR = Memory Address Register يحمل العنوان المطلوب. MDR = Memory Data Register يحمل القيمة اللي بتتنقل. في نموذج المحاضرة عرض MAR يتبع Address Bus وعرض MDR يتبع Data Bus. دول أسماء في نموذج تنفيذ تعليمي، مش Registers تكتب أسماءها مباشرة في RISC-V assembly.'),
s('Read وWrite خطوة بخطوة','للقراءة: ضع العنوان في MAR، أرسل Read، ثم استقبل القيمة في MDR. للكتابة: ضع القيمة في MDR والعنوان في MAR، ثم أرسل Write. العنوان لا يتحول لقيمة البيانات؛ هو المفتاح اللي يوصلّك لها.',{list:['Read: MAR ← A؛ ثم Read؛ ثم MDR ← Memory[A].','Write: MDR ← X؛ MAR ← A؛ ثم Memory[A] ← MDR.']})],takeaway:'Address يجاوب «فين؟»؛ Data يجاوب «إيه؟»؛ Control يجاوب «نعمل إيه ومتى؟».'},
{id:'cpu-cycle',group:'lect1',title:'رحلة تعليمة داخل الـCPU',english:'Fetch · Decode · Execute · Store',minutes:8,source:'Lect1_v3.pdf · pp. 27–30',summary:'اعرف أدوار PC وIR، وشوف التعليمة بتتحول من عنوان إلى نتيجة.',visual:'cycle',sections:[
s('ALU، Registers، CU','الـALU تنفّذ عمليات حسابية ومنطقية. الـRegisters مخازن صغيرة وسريعة للـOperands والنتائج. الـControl Unit ترسل Control Signals لتختار مصادر القيم، وعملية الـALU، ومكان حفظ الناتج. سرعة Registers مقارنة بـRAM سبب أساسي لاستخدامها بكثافة.'),
s('PC مش IR','الـPC يحمل Instruction Address، والـIR يحمل bits التعليمة نفسها بعد جلبها. في مخطط Fetch التعليمي، يُنسخ PC إلى MAR، تُجلب التعليمة إلى IR عبر MDR، ثم يتقدم PC للعنوان التالي. في تعليمات RISC-V الأساسية ذات 32 bit التقدم المتسلسل عادة +4 bytes، والـBranch/Jump يغيّر المسار.'),
s('الخطوات الأربعة','Fetch تجيب التعليمة، Decode تفهم الـOpcode والـOperands، Execute تنفّذ العمل، وStore/Write-back تحفظ الناتج عند الحاجة. كلمة Store في الدورة مفهوم عام؛ مش معناها إن كل تعليمة لازم تنفذ sd أو تكتب في RAM.',{list:['Fetch: قراءة التعليمات من Memory.','Decode: تحديد نوع التعليمة والـRegisters.','Execute: حساب نتيجة أو Effective Address أو قرار Branch.','Write-back / Store: تحديث الوجهة حسب التعليمة.']}),
s('Flags في النموذج العام','المحاضرة تعرض Status Register فيه Zero وNegative وCarry وOverflow. دي فكرة معروفة في بعض المعالجات، لكنها ليست شرطًا في كل ISA. الـRISC-V Base Integer ISA لا تستخدم Condition-code flags register للعمليات المعتادة؛ تعليمات Branch تقارن Registers مباشرة.',{note:'توضيح مرجعي: لا تنقل افتراض وجود Flags من مخطط CPU العام إلى RISC-V.',ref:'isa'}),
s('Cycle تعليمية وليست Timing Simulator','الرسمة هنا تتتبع معنى المراحل. عدد المراحل لا يساوي دائمًا CPI، ولا يعني إن كل تعليمة تأخذ نفس الوقت. التنفيذ الحقيقي يختلف مع Microarchitecture، وعمليات الذاكرة، والـPipeline.')],takeaway:'PC هو عنوان التعليمة؛ IR هو محتوى التعليمة.'},
{id:'evolution',group:'lect1',title:'ليه زيادة الـCores مش كفاية؟',english:'Moore · Dennard · Amdahl',minutes:8,source:'Lect1_v3.pdf · pp. 13–19',summary:'افصل نمو عدد الـTransistors عن الطاقة وعن السرعة، وشوف حدود الـParallelism.',visual:'amdahl',sections:[
s('Moore’s Law','هو اتجاه تاريخي في نمو كثافة وعدد Transistors على الشريحة، وليس وعدًا بأن كل برنامج يتضاعف أداؤه كل سنتين. الأداء يتأثر بالتصميم والذاكرة والطاقة وطبيعة البرنامج. الرسوم في المحاضرة تتناول بيانات تاريخية حتى 2018، فلا نستخدمها لتوقع أداء معالج حديث بعينه.'),
s('Dennard Scaling','الفكرة التاريخية: مع تصغير Transistors وخفض Voltage، تقدر ترفع السرعة مع Power density شبه ثابتة. لما الجهد والتسرب والحرارة أصبحوا قيودًا أصعب، لم يعد رفع Clock rate وحده طريقًا بسيطًا لتحسين الأداء. المحاضرة تربط نهاية الاتجاه تقريبًا بفترة 2004.'),
s('التحول إلى Multicore','بدل Core واحدة بتردد أعلى باستمرار، وجود عدة Cores يساعد لو العمل قابل للتقسيم. لو البرنامج Serial أو الذاكرة هي الاختناق، إضافة Cores لا تعالج المشكلة تلقائيًا. Cache وتحسين الـMicroarchitecture والـSoftware كلها عوامل مهمة.'),
s('Amdahl’s Law','لو s هو الجزء Serial وN عدد الـCores، ومع افتراض توزيع مثالي للجزء الباقي وبدون overhead: Speedup = 1 / (s + (1 − s)/N). الحد الأقصى عندما N يكبر جدًا هو 1/s. لو 20% Serial، أقصى تحسن 5× مهما زوّدت Cores.',{formula:'Speedup = 1 / (s + (1 − s) / N)'}),
s('مثال واقعي في الحساب','برنامج زمنه 100s: جزء Serial = 20s والجزء Parallel = 80s. على 4 Cores، الجزء Parallel يصير 20s في النموذج المثالي، والإجمالي 40s؛ Speedup = 100/40 = 2.5×. مش 4×، لأن الـ20s الأصلية لا تتوزع.'),
s('حدود النموذج','المعادلة تفترض حجم مهمة ثابت وعدم وجود تكاليف إضافية للتواصل أو التزامن. الواقع قد يكون أبطأ من النتيجة المثالية. استخدمها لفهم السقف، وليس لاعتبار كل برنامج متعدد الـThreads سيحقق الرقم نفسه.')],takeaway:'الجزء الذي لا يتحسن يحدد سقف تحسن البرنامج كله.'},
{id:'logic',group:'lab1',title:'قرارات بسيطة من صفر وواحد',english:'Logic Gates & Boolean Algebra',minutes:9,source:'Lab01.pdf · pp. 7–9',summary:'جرّب البوابات وافهم الفرق بين OR وXOR، وبين الجمع المنطقي والجمع الحسابي.',visual:'logic',sections:[
s('Binary وBoolean','في Digital Logic بنمثل الحالات عادة بقيمتين: 0 و1. Boolean Algebra تتعامل مع العمليات على القيم دي. الرمز + في Boolean يعني OR، والضرب أو التجاور يعني AND، والشرطة أو apostrophe تعني NOT. إذًا 1 + 1 منطقيًا = 1، وليس 2.'),
s('عائلة البوابات','AND تحتاج كل Inputs = 1. OR تحتاج على الأقل Input واحدة = 1. XOR ذات مدخلين تخرج 1 لو المدخلان مختلفان. NOT تعكس قيمة واحدة. NAND وNOR وXNOR هي نفي AND وOR وXOR.',{table:{heads:['A','B','AND','OR','XOR','NAND','NOR','XNOR'],rows:[['0','0','0','0','0','1','1','1'],['0','1','0','1','1','1','0','0'],['1','0','0','1','1','1','0','0'],['1','1','1','1','0','0','0','1']]}}),
s('Truth Table','جدول الحقيقة يسرد كل الاحتمالات. لو الدالة فيها n متغيرات مستقلة، عدد الصفوف 2^n. الدالة F = x + y′z لها 3 Inputs وبالتالي 8 صفوف. احسب y′ أولًا، ثم AND مع z، ثم OR مع x.',{formula:'F = x OR ((NOT y) AND z)',table:{heads:['x','y','z','F'],rows:[['0','0','0','0'],['0','0','1','1'],['0','1','0','0'],['0','1','1','0'],['1','0','0','1'],['1','0','1','1'],['1','1','0','1'],['1','1','1','1']]}}),
s('قوانين تساعدك تبسّط','Identity: A + 0 = A وA·1 = A. Complement: A + A′ = 1 وA·A′ = 0. Idempotent: A + A = A. De Morgan: (A·B)′ = A′ + B′، و(A+B)′ = A′·B′. لتتحقق من تبسيط، قارن Truth Tables قبل وبعد.'),
s('تحويل دالة إلى دائرة','الدالة F = x + y′z تحتاج NOT على y، وAND بين الناتج وz، ثم OR مع x. تغيير ترتيب التوصيل ممكن يغيّر الوظيفة؛ مثل (x+y′)z مش نفس التعبير. ارجع للأقواس والـTruth Table عند الشك.')],takeaway:'OR تعني واحد على الأقل؛ XOR ذات مدخلين تعني مختلفين.'},
{id:'circuits',group:'lab1',title:'من Gates إلى دوائر مفيدة',english:'Combinational & Sequential Circuits',minutes:10,source:'Lab01.pdf · pp. 10–16, 23',summary:'جمع واختيار وتخزين: افهم Half-Adder وFull-Adder والـMUX والـFlip-Flop.',visual:'mux',sections:[
s('Combinational vs. Sequential','خرج Combinational circuit يعتمد على Inputs الحالية بعد زمن الانتشار. خرج Sequential circuit يعتمد أيضًا على State مخزنة. الـAdder وMUX أمثلة Combinational؛ Flip-Flop وRegister أمثلة Sequential. وجود State هو الفرق، مش مجرد شكل الدائرة.'),
s('Half-Adder','يجمع bit A وbit B؛ يحتاج نتيجتين لأن 1+1 = 10 بالـBinary. Sum = A XOR B وCarry = A AND B. لا يوجد Carry-in، لذلك وحده لا يكفي لجمع خانة يأتيها Carry من خانة سابقة.',{table:{heads:['A','B','Sum','Carry'],rows:[['0','0','0','0'],['0','1','1','0'],['1','0','1','0'],['1','1','0','1']]},formula:'Sum = A ⊕ B     Carry = A · B'}),
s('Full-Adder','يدخل له A وB وCarry-in. Sum = A XOR B XOR Cin؛ وCout = AB + ACin + BCin. توصيل عدة Full-Adders يجعل كل خانة تسلم Carry للخانة الأعلى. مثلًا A=1 وB=1 وCin=1 يعطي Sum=1 وCout=1، أي 3 بالـDecimal.'),
s('Encoder وDecoder','Decoder يحوّل n input bits إلى اختيار من حتى 2^n outputs. Encoder يعمل عكس الفكرة: يمثل input المختارة بكود binary؛ النسخة العادية تفترض عادة input واحدة فعالة، وPriority Encoder يعالج تعدد المدخلات وفق أولوية. دول أدوات لتوجيه وفهم الإشارات.'),
s('MUX 4×1','الـMultiplexer يختار Input واحدة من أربع، باستخدام Selector bits اثنتين. لو S1S0 = 00 نختار I0؛ 01 تختار I1؛ 10 تختار I2؛ 11 تختار I3. الاختيار لا يجمع كل القيم؛ هو ينقل قيمة Input المختارة.',{formula:'Y = S1′S0′I0 + S1′S0I1 + S1S0′I2 + S1S0I3',table:{heads:['S1','S0','Y'],rows:[['0','0','I0'],['0','1','I1'],['1','0','I2'],['1','1','I3']]}}),
s('D Flip-Flop وRegister','D Flip-Flop يخزن bit واحدة، ويحدث Q عند Clock edge المناسبة حسب التصميم. بين الحواف يحتفظ بالحالة. Register من 64 bit يُمثّل عادة بمجموعة من 64 Flip-Flops. الـClock لا يجعل كل دائرة Sequential؛ المهم وجود ذاكرة حالة وطريقة تحديثها.')],takeaway:'Combinational يحسب من المدخلات؛ Sequential يحتفظ بحالة.'},
{id:'assembly-basics',group:'lab1',title:'اقرأ أول برنامج Assembly',english:'Syntax · Labels · Directives',minutes:9,source:'Lab01.pdf · pp. 18–21, 24',summary:'افهم مكوّنات الملف قبل ما تحفظ أسماء التعليمات.',sections:[
s('RISC-V إيه؟','RISC-V هي Instruction Set Architecture مفتوحة وModular، وليست اسم معالج واحد. تطويرها بدأ في UC Berkeley سنة 2010. الـBase ISA توفر أساسًا ويمكن إضافة Extensions مثل M للضرب والقسمة. RV64 يعني إن XLEN = 64، أي عرض Integer Registers.'),
s('أربع مكوّنات في الملف','Comments لتوضيح الكود، Labels لتسمية مواقع، Instructions للعمل المطلوب، وDirectives لتوجيه الـAssembler. Label تنتهي بنقطتين، وDirective تبدأ غالبًا بنقطة. .word 10 يضع قيمة 32-bit في بيانات البرنامج؛ ليس تعليمة ALU.',{code:'.data\nvalue: .word 10\n.text\nstart:\n  addi a0, x0, 1  # a0 = 1'}),
s('Operands لها أنواع','Register مثل x10 أو alias a0، Immediate مثل 7، وSymbol مثل compute. الـAssembler والـLinker يحولان الرموز وعناوينها. تعليمات arithmetic المعتادة مثل add ترتيبها Destination ثم Source1 ثم Source2.'),
s('Pseudo-instructions','mv وli وj وbeqz وnop أسماء مريحة قد تتحول إلى تعليمات Base ISA. مثل mv a2,a0 تساوي addi a2,a0,0. وnop تساوي addi x0,x0,0. li بقيمة كبيرة قد تتوسع لأكثر من Instruction؛ فلا تحسب IC من عدد سطور الـPseudo-instructions دائمًا.',{ref:'assembly',code:'mv a2, a0   # addi a2, a0, 0\nli a0, 1    # addi a0, x0, 1\nnop         # addi x0, x0, 0'}),
s('قراءة مثال a^b','احفظ a الأصلي في a2، وابدأ الناتج a0 = 1. طالما a1 غير صفر اضرب الناتج في a2 ثم قلل العداد وارجع للحلقة. لما b=0 الناتج 1. المثال يفترض b عددًا صحيحًا غير سالب، وmul تحتاج M extension. قيم ضخمة قد تلتف على عرض Register.',{code:'pow:\n  mv a2, a0\n  li a0, 1\ncompute:\n  beqz a1, finish\n  mul a0, a0, a2\n  addi a1, a1, -1\n  j compute\nfinish:\n  nop',ref:'multiply'}),
s('مثال تعليمي vs. Function كاملة','الكود في اللاب ينتهي بـnop للتوضيح؛ nop لا يرجع للـCaller. Function قابلة للاستدعاء تحتاج اتفاق الـABI وتعليمة عودة مثل ret. هنا بنشرح تتبع المثال نفسه، بدون اعتبار قالب اللاب برنامجًا كاملًا لنظام تشغيل.')],takeaway:'Instruction تنفّذ؛ Directive توجه Assembler؛ Label تسمّي موقعًا.'},
{id:'performance',group:'lect2',title:'مين أسرع؟ احسب الزمن',english:'CPU Time & Relative Performance',minutes:10,source:'Lect2.pdf · pp. 5–11, 14; Lab02.pdf · pp. 4–6, 21',summary:'Clock rate وحده مش مقياس كفاية. اجمع IC وCPI والتردد في معادلة واحدة.',visual:'performance',sections:[
s('السرعة عكس الزمن','لمهمة محددة، Performance = 1 / Execution Time. لو A تنهي في 10s وB في 15s، A أسرع 1.5× لأن PerformanceA / PerformanceB = TimeB / TimeA. خليك دقيق في اتجاه القسمة: الزمن الأقل يعطي الأداء الأعلى.'),
s('Clock period وClock rate','Clock period هو زمن Cycle واحدة. Clock rate هو عدد الـCycles في الثانية؛ إذًا T = 1/f. تردد 4 GHz يعني 4×10^9 cycles/s، وبالتالي Cycle time = 0.25 ns = 250 ps. GHz = 10^9 Hz، وns = 10^-9 s، وps = 10^-12 s.',{formula:'Clock period = 1 / Clock rate'}),
s('المعادلة الأساسية','عدد Cycles = Instruction Count × Average CPI. CPU time = Cycles × Clock period = IC × CPI / Clock rate. استخدم Dynamic IC، يعني التعليمات التي نُفّذت فعلًا، بما فيها تكرار Loop. CPU time هنا لا يشمل كل انتظار I/O أو أعمال النظام في Elapsed time.',{formula:'CPU Time = IC × CPI / Clock Rate'}),
s('مثال Lab02: جهازان','A: IC=1,000,000 وCPI=2 و2GHz؛ Cycles=2,000,000 والزمن=1ms. B: IC=800,000 وCPI=3 و2.5GHz؛ Cycles=2,400,000 والزمن=0.96ms. B أسرع رغم CPI الأكبر، بنسبة 1/0.96 ≈ 1.0417×. تقليل الزمن 4% ليس نفس نسبة زيادة الأداء 4.17%.', {formula:'TA = 1.00 ms     TB = 0.96 ms     SpeedupB/A ≈ 1.0417×'}),
s('مثال Cycle Time','A: 250ps وCPI=2؛ الزمن لكل Instruction في المتوسط = 500ps. B: 500ps وCPI=1.2؛ المتوسط = 600ps. لنفس IC من مليون: A=0.5ms وB=0.6ms؛ A أسرع 1.2×. وجود CPI أقل في B لم يعوض Clock period الأطول.'),
s('Compiler Optimization','لو IC يقل 20% وCPI يزيد 15%، والتردد ثابت: Tnew/Told = 0.8×1.15 = 0.92. الزمن يقل 8%؛ الأداء يزيد بنسبة 1/0.92−1 ≈ 8.70%. لا تجمع النسب: العوامل تتضرب.')],takeaway:'قارن CPU Time لنفس المهمة، ثم اقسم زمن الأبطأ على زمن الأسرع.'},
{id:'cpi-mix',group:'lect2',title:'مش كل Instruction تكلفتها واحدة',english:'Instruction Mix & Weighted CPI',minutes:8,source:'Lect2.pdf · pp. 9–14',summary:'Average CPI متوسط موزون بعدد التعليمات من كل Class.',visual:'mix',sections:[
s('Instruction Classes','لو تعليمات Class A تأخذ 1 Cycle وB تأخذ 2 وC تأخذ 3، لا يصح جمع CPI وقسمتها على 3 إلا لو أعدادهم متساوية. حساب Cycles أولًا أو استخدام نسب الـMix يعطي المتوسط الصحيح.',{formula:'Cycles = Σ(ICᵢ × CPIᵢ)     Average CPI = Cycles / Total IC'}),
s('Sequence 1 في المحاضرة','عدد A=2 وB=1 وC=2. IC=5. Cycles=2×1+1×2+2×3=10. Average CPI=10/5=2. التنفيذ فيه خمس Instructions لكن محتاج عشر Cycles في نموذج المثال.'),
s('Sequence 2 في المحاضرة','عدد A=4 وB=1 وC=1. IC=6. Cycles=4×1+1×2+1×3=9. Average CPI=9/6=1.5. Sequence 2 أسرع عند نفس Clock، رغم إنها أطول بعدد التعليمات.',{table:{heads:['Sequence','IC','Cycles','Average CPI'],rows:[['1','5','10','2.0'],['2','6','9','1.5']]}}),
s('لو الـMix بالنسب','لو البرنامج 50% Class A (CPI=1)، و30% B (CPI=2)، و20% C (CPI=4): Average CPI=0.5×1+0.3×2+0.2×4=1.9. مجموع نسب الـMix يجب أن يساوي 100%.'),
s('العوامل مرتبطة','Algorithm والـLanguage والـCompiler والـISA تؤثر على IC وMix. الـMicroarchitecture تؤثر على تكلفة التنفيذ والـClock. تغيير عامل ممكن يغيّر غيره؛ لذلك ارجع لمعادلة CPU Time في كل مقارنة.')],takeaway:'برنامج فيه Instructions أكثر قد ينفّذ أسرع لو عدد الـCycles أقل.'},
{id:'registers',group:'lect2',title:'المساحة السريعة جنب الـALU',english:'RISC-V Registers & ABI',minutes:8,source:'Lect2.pdf · pp. 24–26, 31, 37; Lab02.pdf · pp. 8–9',summary:'32 Integer Registers، ولكل اسم رقمي اسم ABI ودور متعارف عليه.',sections:[
s('RV64 وRV32','في RV64I يوجد 32 Integer Registers من x0 إلى x31، كل واحد 64 bit. في RV32I نفس العدد لكن العرض 32 bit. العرض مش حجم كل Instruction: تعليمات Base ISA تظل 32 bit. الأمثلة التي تستخدم ld وsd هنا RV64.',{ref:'rv64'}),
s('x0 حالة خاصة','قراءة x0 تعطي صفرًا دائمًا، والكتابة فيه تتجاهَل القيمة. لذلك add x5,x6,x0 ينسخ x6، وsub x5,x0,x6 يحسب سالب x6. وجود x0 يبسط حالات كثيرة من غير Register تحتاج تهيئته بصفر.'),
s('أسماء ABI','الاسم x10 والاسم a0 يشيران لنفس Register، مش مكانين مختلفين. الـABI تحدد اتفاقًا بين البرامج والدوال: أين Arguments، وأين Return values، ومن مسؤول عن حفظ قيم Registers عبر Function call.',{table:{heads:['Registers','Aliases','الدور'],rows:[['x0','zero','صفر ثابت'],['x1','ra','Return address'],['x2','sp','Stack pointer'],['x3 / x4','gp / tp','Global / Thread pointer'],['x5–x7','t0–t2','Temporaries'],['x8 / x9','s0(fp) / s1','Saved؛ x8 قد يُستخدم Frame pointer'],['x10–x17','a0–a7','Arguments؛ a0/a1 لنتائج مناسبة'],['x18–x27','s2–s11','Saved registers'],['x28–x31','t3–t6','Temporaries']]},ref:'abi'}),
s('تصحيح أسماء الـSaved','x8 هو s0 ويمكن استخدامه fp، وx9 هو s1، ومع x18–x27 (s2–s11) يصبح العدد 12 Saved Registers. لا تعتبر x9 مع x18–x27 وحدهم 12؛ العدد في المجموعة دي 11. Frame pointer اختياري وفق البرنامج والـABI.'),
s('Registers vs. Memory','Registers صغيرة وسريعة، لكن عددها محدود. الـCompiler يحاول إبقاء القيم كثيرة الاستخدام فيها؛ لو لا تكفي، يحدث Register spilling إلى Memory. أرقام 200× و10,000× المعروضة في المحاضرة أمثلة تاريخية، وليست ضمانًا ثابتًا لكل Hardware.'),
s('Smaller is faster','زيادة عدد Registers قد تزيد حجم الدوائر ومسافة الإشارات وصعوبة الوصول. الفكرة Design principle وليست قاعدة تمنع كل تصميم أكبر؛ اختيار العدد موازنة بين أداء Hardware وضغط الـRegister allocation في Software.')],takeaway:'Aliases أسماء لنفس Registers؛ RV64 عرض البيانات وليس طول كل Instruction.'},
{id:'arithmetic',group:'lect2',title:'حوّل المعادلة إلى تعليمات',english:'add · sub · addi',minutes:9,source:'Lect2.pdf · pp. 18–21, 26, 32; Lab02.pdf · p. 14',summary:'قسّم التعبير الكبير إلى عمليات صغيرة، واحفظ النتائج المؤقتة.',visual:'assembly',sections:[
s('Three operands','add rd,rs1,rs2 تعني rd=rs1+rs2. sub rd,rs1,rs2 تعني rd=rs1−rs2. الـDestination أول Operand. المدخلات Registers؛ لا يمكن كتابة add مباشرة بين قيمتين في RAM. اقرأ Source values أولًا ثم اكتب النتيجة، لذلك add x5,x5,x6 صحيحة.'),
s('مثال المحاضرة','نفترض f في x19، وg,h,i,j في x20,x21,x22,x23. لتقييم f=(g+h)−(i+j)، احسب الجمعين في x5 وx6 ثم اطرح. لو g=8 وh=4 وi=3 وj=2، الناتج 7.',{code:'add x5, x20, x21  # g + h\nadd x6, x22, x23  # i + j\nsub x19, x5, x6   # f = 12 - 5 = 7'}),
s('Immediate هو Constant في التعليمة','addi x22,x22,4 تزيد القيمة 4 دون Load من Memory. الـImmediate هنا signed 12-bit ومجاله −2048 إلى +2047. الشريحة 32 في Lect2 تعرض 11-bit ومدى −1024..1023؛ ده خطأ في الشريحة مقارنة بالـISA الرسمي.',{formula:'addi Immediate: 12 bits → −2048 … +2047',note:'تصحيح موثّق: نعتمد signed 12-bit للـaddi، كما تحدده RISC-V ISA.',ref:'isa'}),
s('ليه مفيش subi؟','addi تقبل قيمة سالبة، فيمكن طرح 7 باستخدام addi x5,x5,-7. القيمة ثابتة ومشفرة في التعليمة. لو constant لا يناسب المجال، يستخدم Assembler/Compiler سلسلة مناسبة؛ li قد تكون pseudo-instruction بأكثر من تعليمة.'),
s('Simplicity favors regularity','تكرار صيغة منتظمة يجعل Hardware decoding أبسط. Make the common case fast معناها دعم الحالات الشائعة مثل constants الصغيرة بكفاءة. عبارة «كل التعليمات ثلاث Operands» تبسيط خاطئ؛ الصيغة تخص أمثلة Arithmetic، لكن nop وret وInstructions أخرى تختلف.'),
s('نتيجة على عرض محدود','Integer add/sub في RISC-V لا تعمل Arithmetic overflow trap تلقائيًا؛ النتيجة تُحفظ ضمن XLEN. المثال التفاعلي يحافظ على RV64 باستخدام 64-bit values. الرصد المطلوب للـOverflow يمكن تنفيذه بكود مناسب عندما يحتاجه البرنامج.',{ref:'isa'})],takeaway:'رتّب الـOperands، قسّم الحساب، واستخدم addi للقيم الصغيرة الموقعة.'},
{id:'load-store',group:'lect2',title:'من الـArray إلى العنوان',english:'Byte Addressing · Load · Store',minutes:11,source:'Lect2.pdf · pp. 22, 27–30; Lab02.pdf · pp. 10–11, 15–16, 20',summary:'الـIndex مش هو الـOffset. اضربه في حجم العنصر بالـBytes.',visual:'address',sections:[
s('Byte-addressed Memory','كل عنوان في RISC-V يحدد Byte ذات 8 bits. Word = 32 bit = 4 bytes؛ Doubleword = 64 bit = 8 bytes. سجل RV64 سعته Doubleword، لكن ممكن تعمل Load لجزء أصغر. نوع عناصر الـArray هو الذي يحدد المسافة بين عناصرها.',{table:{heads:['النوع','Bits','Bytes','Load / Store'],rows:[['Byte','8','1','lb / sb'],['Halfword','16','2','lh / sh'],['Word','32','4','lw / sw'],['Doubleword','64','8','ld / sd']]}}),
s('Effective Address','عنوان A[i] = Base Address + i × Element Size. الصيغة offset(rs1) تستخدم قيمة Base Register زائد signed byte offset. لو x22=4096، A[8] من Doublewords تكون في 4096+8×8=4160.',{formula:'Effective Address = Base + Index × Bytes per element'}),
s('Load ثم حساب ثم Store','لتنفيذ A[12]=h+A[8]، وh في x21 والـBase في x22 وعناصر 64 bit: ld يقرأ A[8] من offset 64، add يحسب في Register، ثم sd يكتب النتيجة إلى offset 96. في sd أول Operand هو Source Register للقيمة، وليس Destination Register.',{code:'ld x9, 64(x22)    # x9 = A[8]\nadd x9, x21, x9   # x9 = h + A[8]\nsd x9, 96(x22)    # A[12] = x9'}),
s('Sign Extension','في RV64، lb وlh وlw توسع القيمة الموقعة إلى 64 bit. لو Byte = 11111111، lb يعطي −1؛ lbu يوسع بصفر فيعطي 255. ld ينقل 64 bit كاملة. Store أصغر مثل sb يكتب أقل 8 bits من Register.',{ref:'rv64'}),
s('Natural Alignment','Word يكون Naturally aligned لو العنوان divisible by 4، وDoubleword لو divisible by 8. مثال: 4096 مناسب لـld، و4098 ليس Naturally aligned لها. الوصول Misaligned قد يُدعم أو يسبب Trap حسب Execution Environment؛ ليست قاعدة مطلقة أن كل وصول غير محاذٍ ممنوع.',{note:'Lab02 يقدم المحاذاة كقاعدة مبسطة؛ المواصفة تجعل سلوك Misaligned dependent on the execution environment.',ref:'isa'}),
s('نوع عناصر B في Task01','نص Lab02 Task01 لا يحدد حجم عناصر B. لو Doublewords استخدم ld/sd وOffsets 8 و24. لو Words استخدم lw/sw وOffsets 4 و12. الإجابة تحتاج افتراضًا معلنًا، لأن RV64 لا يعني أن كل Array عناصرها 64 bit.')],takeaway:'Offset بالـBytes؛ Load إلى Register؛ Store من Register.'},
{id:'binary',group:'lect2',title:'نفس الـBits، معنيان مختلفان',english:'Unsigned & Two’s Complement',minutes:9,source:'Lect2.pdf · pp. 33–35; Lab02.pdf · p. 11',summary:'1111 ممكن تكون 15 أو −1؛ التفسير هو اللي يحدد المعنى.',visual:'binary',sections:[
s('Unsigned','في n bits، المجال من 0 إلى 2^n−1. كل bit وزنها موجب: من اليمين 1،2،4،8… مثل 1011 في 4 bits تعني 8+2+1=11.',{formula:'Unsigned range: 0 … 2ⁿ − 1'}),
s('Two’s Complement','في التفسير Signed، وزن أعلى bit هو −2^(n−1) بدل موجب. الباقي يحتفظ بأوزانه. في 4 bits، 1100 = −8+4 = −4، و1111=−8+4+2+1=−1. المجال −2^(n−1) إلى 2^(n−1)−1؛ فيه قيمة سالبة إضافية لأن الصفر يأخذ مكانًا.',{formula:'Signed range: −2ⁿ⁻¹ … 2ⁿ⁻¹ − 1'}),
s('إزاي تجيب السالب؟','مثّل +2 على 8 bits: 00000010. اعكس الـBits فتحصل على 11111101، وأضف 1 فتحصل على 11111110، وهي −2. الخطوات دي تعمل داخل عرض ثابت؛ لو غيرت عدد الـBits، غيّر التمثيل accordingly.',{code:'+2: 00000010\nNOT: 11111101\n +1: 11111110 = -2'}),
s('حالة الحد الأدنى','في 4-bit Signed، −8 = 1000. نفيها على نفس العرض يعطي 1000 مرة أخرى لأن +8 خارج المجال. دي Overflow. لا توجد قيمة +8 في هذا التمثيل؛ لا تستخدم النفي لإثبات أن كل قيمة لها مقابل موجب داخل نفس العرض.'),
s('Sign Extension','لتوسيع signed number كرر Sign bit؛ 4-bit 1100 (−4) يصير 8-bit 11111100. لتوسيع unsigned استخدم أصفارًا؛ 1100 كـunsigned (12) يصير 00001100. تغيير العرض لازم يحافظ على تفسير القيمة.'),
s('64-bit limits','Unsigned RV64 range: 0 إلى 18,446,744,073,709,551,615. Signed: −9,223,372,036,854,775,808 إلى 9,223,372,036,854,775,807. توجد أخطاء مطبعية في الرقم Unsigned بالشريحة 33؛ الصيغة 2^64−1 هي المرجع الحسابي الصحيح.')],takeaway:'الـBits وحدها لا تحدد Signedness؛ عدد الـBits وطريقة التفسير جزء من المعنى.'},
{id:'formats',group:'lab2',title:'إزاي التعليمة تبقى Bits؟',english:'Instruction Formats & Toolchain',minutes:10,source:'Lab02.pdf · pp. 11–13, 17–18; Lect2.pdf · p. 4',summary:'اقرأ حقول R-type وافهم دور Compiler وAssembler وLinker وLoader.',visual:'format',sections:[
s('Levels of Program Code','High-level language قريبة من المشكلة. Assembly تمثيل نصي لتعليمات الـISA. Machine code هي Binary encoding التي يفهمها المعالج. ترجمة سطر C قد تنتج عدة Instructions؛ لذلك عدد الأسطر لا يحدد IC.'),
s('حقول R-type','التعليمة add x5,x20,x21 تتضمن Opcode وfunct3 وfunct7 لتحديد العملية، rd للوجهة، وrs1 وrs2 للمصدرين. كل رقم Register يحتاج 5 bits لتمثيل 32 احتمالًا. مجموع حقول R-type: 7+5+5+3+5+7=32 bits.',{formula:'funct7 | rs2 | rs1 | funct3 | rd | opcode'}),
s('عائلات الصيغ','R للعمليات بين Registers، I للـImmediate وLoads، S للـStores، B للـBranches، U للـUpper immediate، J للـJump. Lab02 يسرد خمس صيغ ويترك U؛ أضفناها ليكون التصور كاملًا. B وJ لها توزيع خاص للـImmediate؛ لا تعمم مجال addi عليها.',{table:{heads:['Format','أمثلة','الفكرة'],rows:[['R','add, sub','مصدران ووجهة'],['I','addi, ld','مصدر وImmediate ووجهة'],['S','sd','عنوان وقيمة تكتب إلى Memory'],['B','beq','مقارنة وفرع'],['U','lui, auipc','Upper immediate'],['J','jal','Jump مع Return address']]},ref:'isa'}),
s('32-bit Base Instructions','في Base Integer ISA الصيغ الأساسية طولها 32 bit. هذا مستقل عن RV32/RV64. C extension تضيف تعليمات compressed طولها 16 bit؛ إذًا «كل RISC-V instruction طولها 32-bit» صحيحة فقط في سياق الـBase المستخدم هنا.',{ref:'isa'}),
s('Compilation Toolchain','Compiler يحول C إلى Assembly؛ Assembler يحولها إلى Object file مع Machine code وRelocations؛ Linker يربط الملفات والمكتبات ويحل الرموز؛ Loader يضع البرنامج في Memory في بيئة التشغيل المناسبة. في Bare-metal قد تختلف مرحلة التحميل حسب النظام.',{list:['C source → Compiler → Assembly','Assembly → Assembler → Object file','Objects + libraries → Linker → Executable','Executable → Loader → Memory']}),
s('التجربة على Simulator','Lab02 يقترح CPUlator للتجميع والتتبع. تأكد من النظام والـISA المدعومة قبل نسخ المثال؛ ld/sd تحتاج RV64 وmul تحتاج M. الموقع هنا يقدم تتبعًا تعليميًا لثلاثة أمثلة محددة، ويمكنك الرجوع لأداة تدعم RV64 لتشغيل برامج كاملة.')],takeaway:'عرض Register مختلف عن طول Instruction؛ Toolchain مراحل ولكل مرحلة وظيفة.'},
{id:'lab-tasks',group:'lab2',title:'حل اللابات بفهم كل خطوة',english:'Worked Lab Tasks',minutes:12,source:'Lab01.pdf · pp. 23–24; Lab02.pdf · pp. 5–6, 20–21',summary:'حلول تعليمية للـMUX وa³ وترجمة Arrays ومقارنة الأداء، مع توضيح الافتراضات.',visual:'assembly',sections:[
s('Lab01 · Task01 · MUX 4×1','ارسم أربع خطوط I0..I3 داخلة لـMUX، وخطي S1 وS0 للاختيار، وخط Y خارج. جدول الاختيار: 00→I0، 01→I1، 10→I2، 11→I3. لو S1S0=10 وI2=1 يكون Y=1 بغض النظر عن باقي Inputs. الرسم التفاعلي في درس Circuits يتيح تجربة كل الاختيارات.'),
s('Lab01 · Task02 · a³','احفظ a الأصلي لأن a0 هيتغير. حل مباشر من غير Loop: mv t0,a0 ثم mul a0,a0,t0 (a²) ثم mul a0,a0,t0 (a³). ده يحتاج M extension، ويفترض أن النتيجة المطلوبة هي أقل XLEN bits عند Overflow.',{code:'pow:\n  mv t0, a0\ncompute:\n  mul a0, a0, t0\n  mul a0, a0, t0\nfinish:\n  nop   # end of the lab snippet'}),
s('حل a³ باستخدام أسلوب Loop','بنفس فكرة مثال a^b في اللاب: احفظ a في a2، ضع 3 في العداد a1، واجعل accumulator =1. اضرب وقلل العداد حتى يصل صفر. ده أقرب لقالب الحلقة الموجود، وتقدر تقارن تكلفة الحلين. في Function حقيقية استخدم ret عند العودة؛ nop هنا كما في قالب اللاب.',{code:'pow:\n  mv a2, a0\n  li a1, 3\n  li a0, 1\ncompute:\n  beqz a1, finish\n  mul a0, a0, a2\n  addi a1, a1, -1\n  j compute\nfinish:\n  nop'}),
s('Lab02 · Task01 · B[3] = B[1] + 7','بافتراض Doubleword elements والـBase في x20: offset B[1]=8 وB[3]=24. Load في t0=x5، أضف 7 باستخدام addi، ثم Store. لو B[1]=12 تصبح B[3]=19. الـBase Register يحتفظ بالعنوان ولا نغيره.',{code:'# RV64, B elements are 64-bit\nld x5, 8(x20)\naddi x5, x5, 7\nsd x5, 24(x20)\n\n# Alternative: B elements are 32-bit\nlw x5, 4(x20)\naddi x5, x5, 7\nsw x5, 12(x20)'}),
s('Lab02 · Task02 · مقارنة الجهازين','لنفس مليون Instruction: A الزمن=10^6×2×250×10^-12=0.0005s=0.5ms. B الزمن=10^6×1.2×500×10^-12=0.0006s=0.6ms. A أسرع بمعامل 0.6/0.5=1.2. انتبه: CPI أقل لا تعني جهازًا أسرع لو Clock period أطول.'),
s('مراجعة قبل تسليم حل','اكتب المعطيات والافتراضات، خصوصًا نوع عناصر Array، ثم القانون، ثم التعويض بالوحدات، ثم النتيجة وتفسيرها. في Assembly علّق دور كل Register وتتبع القيم يدويًا. الحلول هنا للمذاكرة؛ راجع تنسيق ومتطلبات اللاب مع مدرسك.')],takeaway:'الحل الجيد يوضح الافتراضات ويشرح سبب كل Instruction أو خطوة حساب.'}
];
export const glossary=[
['ISA','Instruction Set Architecture','عقد يحدد التعليمات والـRegisters والسلوك الذي يراه البرنامج.','abstraction'],['Microarchitecture','Microarchitecture','تنفيذ الـISA في دوائر Hardware.','abstraction'],['ALU','Arithmetic Logic Unit','جزء CPU الذي ينفّذ الحساب والعمليات المنطقية.','cpu-cycle'],['CU','Control Unit','جزء ينسق التنفيذ ويرسل Control signals.','cpu-cycle'],['PC','Program Counter','Register يحمل عنوان التعليمة؛ يتقدم أو يتغير مع Branch/Jump.','cpu-cycle'],['IR','Instruction Register','يحمل bits التعليمة الجاري فكها وتنفيذها في النموذج التعليمي.','cpu-cycle'],['MAR','Memory Address Register','يحمل عنوان الموقع المراد الوصول إليه في النموذج العام.','memory-buses'],['MDR','Memory Data Register','يحمل البيانات المتبادلة مع Memory في النموذج العام.','memory-buses'],['Bus','Bus','مسار اتصال لنقل Address أوData أوControl.','memory-buses'],['CPI','Cycles Per Instruction','متوسط عدد Clock cycles لكل Instruction منفذة.','cpi-mix'],['IC','Instruction Count','عدد التعليمات المنفذة فعليًا؛ يشمل تكرارات Loops.','performance'],['Clock Rate','Clock Frequency','عدد Cycles في الثانية؛ معكوس Clock period.','performance'],['ABI','Application Binary Interface','اتفاق بين البرامج والدوال يشمل استخدام Registers وطريقة الاستدعاء.','registers'],['XLEN','Integer Register Width','عرض Integer Registers؛ 64 في RV64 و32 في RV32.','registers'],['Immediate','Immediate Operand','Constant مشفرة داخل Instruction.','arithmetic'],['Offset','Byte Offset','إزاحة بالـBytes تضاف إلى Base address.','load-store'],['Sign Extension','Sign Extension','توسيع Signed value بتكرار Sign bit.','binary'],['MUX','Multiplexer','دائرة تختار Input واحدة من عدة Inputs.','circuits'],['Flip-Flop','Flip-Flop','عنصر Sequential لتخزين bit.','circuits'],['Pseudo-instruction','Pseudo-instruction','اسم Assembly يتحول إلى Instruction أو أكثر.','assembly-basics'],['Directive','Assembler Directive','توجيه للـAssembler مثل .word، وليس عملية CPU.','assembly-basics'],['Load/Store','Load/Store Architecture','الحساب في Registers والوصول للذاكرة بتعليمات منفصلة.','load-store'],['Amdahl’s Law','Amdahl’s Law','حد التحسن عند تحسين جزء فقط من تنفيذ المهمة.','evolution'],['Two’s Complement','Two’s Complement','طريقة تمثيل Signed integers بوزن سالب لأعلى bit.','binary']
];
for(const group of groups){
 group.arabic={title:group.title,desc:group.desc};
 Object.assign(group,englishGroups[group.id]);
}
for(const lesson of lessons){
 const translation=englishLessons[lesson.id];
 if(!translation||translation.sections.length!==lesson.sections.length)throw new Error(`Incomplete translation: ${lesson.id}`);
 lesson.arabic={title:lesson.title,summary:lesson.summary,takeaway:lesson.takeaway};
 lesson.title=lesson.english;
 lesson.summary=translation.summary;
 lesson.takeaway=translation.takeaway;
 lesson.sections=lesson.sections.map((section,index)=>({
  ...section,
  arabic:{body:section.body,list:section.list,note:section.note},
  ...translation.sections[index]
 }));
}

for(const term of glossary){term.arabic=term[2];term[2]=glossaryEnglish[term[0]];}
