export const glossaryEnglish={
'ISA':'The contract specifying the instructions, registers, and behavior visible to software.',
'Microarchitecture':'The hardware circuits and execution strategy that implement an ISA.',
'ALU':'The CPU component that performs arithmetic and logical operations.',
'CU':'The component that coordinates execution and generates control signals.',
'PC':'A register holding an instruction address; sequential execution, branches, and jumps update it.',
'IR':'Holds the fetched instruction bits in the teaching CPU model.',
'MAR':'Holds the requested memory address in the general CPU model.',
'MDR':'Holds the data transferred to or from memory in the general CPU model.',
'Bus':'A communication path carrying addresses, data, or control signals.',
'CPI':'The average number of clock cycles per executed instruction.',
'IC':'The number of instructions actually executed, including repeated loop iterations.',
'Clock Rate':'The number of cycles per second; the inverse of the clock period.',
'ABI':'Conventions between programs and functions, including register roles and calling conventions.',
'XLEN':'The integer register width: 64 bits in RV64 and 32 bits in RV32.',
'Immediate':'A constant encoded within an instruction.',
'Offset':'A displacement in bytes added to a base address.',
'Sign Extension':'Widening a signed value by replicating its sign bit.',
'MUX':'A circuit selecting one input from several inputs.',
'Flip-Flop':'A sequential storage element that holds one bit.',
'Pseudo-instruction':'An assembly name that expands into one or more machine instructions.',
'Directive':'An instruction to the assembler, such as .word, rather than a CPU operation.',
'Load/Store':'An architecture in which arithmetic uses registers and separate instructions access memory.',
'Amdahl’s Law':'The speedup limit when only part of a task is improved.',
'Two’s Complement':'A signed-integer representation with a negative weight for the highest bit.'
};
