const e=(title,body,extra={})=>({title,body,...extra});
export const englishLessons={
'abstraction':{summary:'Each level hides the details below it. Understanding how the levels connect is the first step toward understanding a computer.',takeaway:'The ISA defines behavior; the microarchitecture defines how that behavior is implemented.',sections:[
e('Why study computer architecture?','A program can be correct and still run slowly. To explain why, you need to understand how the processor reads data, how many instructions it executes, and how often it accesses memory. Computer architecture connects software to hardware. Start by tracing a small program and calculating its execution cost.'),
e('Levels of abstraction','Think of a ladder: applications, operating systems, instructions and registers, datapath and control, logic gates, and transistors. Each level uses a defined interface instead of exposing every electronic detail. The operating system manages resources such as memory and devices; applications use its services.',{list:['Application: the task the user wants to perform.','Operating system: manages memory, I/O, and processes.','ISA: the instructions and registers available to software.','Microarchitecture: the circuits and execution strategy that implement the ISA.','Digital logic: gates, adders, and flip-flops.']}),
e('Architecture vs. microarchitecture','Architecture is the interface visible to the programmer: instructions, registers, and memory-access behavior. Microarchitecture is the hardware implementation of that interface. A simple processor and a pipelined processor can implement the same ISA while requiring different cycle counts and delivering different performance.',{table:{heads:['Comparison','Architecture / ISA','Microarchitecture'],rows:[['Main question','What can the program do?','How does the hardware execute it?'],['Example','add and 32 registers','ALU, control, and pipeline'],['Effect','Software and instruction compatibility','Speed, power, and cost']]}}),
e('One instruction, two viewpoints','add x5, x6, x7 adds two register values and writes the result to x5. That meaning belongs to the ISA. Whether it takes one cycle or several, and whether another instruction starts before it finishes, are microarchitectural choices. Identical instruction behavior does not guarantee identical speed.'),
e('Your study roadmap','Start with system components, then digital logic, performance, and RISC-V. Pipelining, Verilog, and memory systems are listed as later course goals, but their detailed treatment is outside the four supplied files.')
]},
'von-neumann':{summary:'Instructions and data live in memory. A processor fetches, executes, and communicates with the outside world.',takeaway:'Stored-program means that program instructions can be stored and read from memory, just like data.',sections:[
e('From wiring to stored programs','In early systems, changing the task could require changing wiring or configuration. The stored-program idea made the program itself information that could be stored and fetched. A new task could be specified without rebuilding the circuit for every problem.'),
e('The five components','The Von Neumann model contains memory, a processing unit, a control unit, input, and output. The ALU performs arithmetic and logic; the control unit coordinates execution. Modern CPUs combine an ALU, control hardware, and registers.',{list:['Memory: stores instructions and data.','ALU: performs arithmetic and logical operations.','Control unit: coordinates timing and execution.','Input: incoming data, such as keyboard input.','Output: outgoing results, such as a display.']}),
e('What does shared memory mean?','In the classical model, instructions and data share memory. The processor must transfer both over communication paths, which helps explain the Von Neumann bottleneck. Modern processors may have separate instruction and data caches internally. The model is a useful introduction rather than a literal description of every processor detail.'),
e('I/O from the CPU’s viewpoint','In memory-mapped I/O, some addresses refer to device registers instead of RAM. Reading or writing those addresses interacts with the device. Some ISAs also provide dedicated I/O instructions. A touchscreen or network card can provide both input and output.'),
e('Trace a simple request','To add two numbers, input supplies the values; memory holds the data and program; the control unit fetches instructions; registers hold operands; the ALU adds them; and the result is saved or displayed. The components cooperate: memory does not calculate, and the ALU does not independently choose the next instruction.')
]},
'memory-buses':{summary:'Separate the location of data from the data itself, and calculate memory capacity from its address and data widths.',takeaway:'Address answers “where?”; data answers “what?”; control answers “which operation, and when?”.',sections:[
e('Types of bus','A bus provides communication between system components. The data bus carries values, the address bus identifies locations, and the control bus carries signals such as Read and Write. Data-bus width and address-bus width need not be equal.',{table:{heads:['Bus','Role','Example'],rows:[['Address','Identifies the location','Address 4096'],['Data','Carries the contents','Value 27'],['Control','Specifies operation and timing','Read or Write']]}}),
e('Count the addressable locations','With n address bits, there are 2^n possible addresses. Total capacity also depends on the size of each location: Capacity = 2^n × bits per location. In byte-addressed memory, each address identifies one byte. A 16-bit address bus can identify 65,536 bytes, or 64 KiB.'),
e('The k × m notation','A 4M × 16-bit chip contains 4M locations, each holding 16 bits. If M = 2^20, its capacity is 2^22 × 16 bits = 2^26 bits = 8 MiB, and selecting a location requires 22 address bits. Distinguish a chip with 16-bit locations from a RISC-V memory system with byte addresses.'),
e('MAR and MDR','MAR, the Memory Address Register, holds the requested address. MDR, the Memory Data Register, holds the value being transferred. In the lecture’s model, MAR width follows the address bus and MDR width follows the data bus. These are teaching-model implementation registers, not register names you can directly use in RISC-V assembly.'),
e('Read and write, step by step','To read, put the address in MAR, issue Read, and receive the value in MDR. To write, put the value in MDR and the address in MAR, then issue Write. The address identifies the data; it is not the data itself.',{list:['Read: MAR ← A; issue Read; MDR ← Memory[A].','Write: MDR ← X; MAR ← A; Memory[A] ← MDR.']})
]},
'cpu-cycle':{summary:'Understand PC and IR, and follow an instruction from its address to its result.',takeaway:'PC holds an instruction address; IR holds the fetched instruction.',sections:[
e('ALU, registers, and control','The ALU performs arithmetic and logical operations. Registers are small, fast storage locations for operands and results. The control unit sends signals that select operand sources, the ALU operation, and the result destination. Fast register access is a major reason to keep frequently used values there.'),
e('PC is different from IR','PC holds an instruction address. IR holds the instruction bits after fetching. In the teaching model, PC is copied to MAR and the instruction reaches IR through MDR. For sequential execution of 32-bit base RISC-V instructions, the next address is normally PC + 4 bytes; branches and jumps change the path.'),
e('The four stages','Fetch obtains the instruction, Decode identifies its opcode and operands, Execute performs the operation, and Store/Write-back updates the destination when needed. “Store” here is a general stage name: it does not mean that every instruction executes sd or writes to RAM.',{list:['Fetch: read the instruction from memory.','Decode: identify the instruction and registers.','Execute: compute a result, an effective address, or a branch decision.','Write-back / Store: update the destination specified by the instruction.']}),
e('Flags in the general CPU model','The lecture shows status flags such as Zero, Negative, Carry, and Overflow. Some processors use them, but they are not universal. The base RISC-V integer ISA does not use a condition-code flags register for ordinary arithmetic; conditional branches compare registers directly.',{note:'Reference clarification: do not carry the flags assumption from a general CPU diagram into base RISC-V.'}),
e('A teaching cycle, not a timing simulator','The diagram explains the meaning of execution stages. The number of stages is not necessarily the CPI, and instructions need not take equal time. Actual timing depends on microarchitecture, memory operations, and pipelining.')
]},
'evolution':{summary:'Separate transistor growth from power and performance, and explore the limits of parallel execution.',takeaway:'The part that does not improve limits the speedup of the whole program.',sections:[
e('Moore’s law','Moore’s law describes a historical trend in transistor counts and density, not a promise that every program doubles its performance every two years. Performance also depends on design, memory, power, and the workload. The lecture charts contain historical data through 2018; they do not predict the performance of a particular modern processor.'),
e('Dennard scaling','Historically, smaller transistors and lower voltage allowed higher speed with roughly constant power density. Voltage, leakage, and heat eventually became harder constraints, so increasing clock rate alone became a less straightforward way to improve performance. The lecture associates this change approximately with 2004.'),
e('The move to multicore','Multiple cores can improve performance when work can be divided among them. A serial program or a memory bottleneck does not automatically become faster with more cores. Caches, microarchitecture, and software also matter.'),
e('Amdahl’s law','Let s be the serial fraction and N the number of cores. For a fixed task, ideal parallel scaling, and no overhead, Speedup = 1 / (s + (1 − s)/N). As N approaches infinity, the limit is 1/s. With a 20% serial fraction, the maximum ideal speedup is 5×.'),
e('A worked example','A program takes 100 s: 20 s is serial and 80 s is parallel. With four cores, the parallel part ideally takes 20 s, giving 40 s overall. Speedup = 100/40 = 2.5×. The original 20 s of serial work cannot be divided among the cores.'),
e('Limits of the model','The equation assumes a fixed task size and no additional communication or synchronization cost. Real execution may be slower than the ideal prediction. Use it to understand a speedup ceiling, rather than expecting every multithreaded program to achieve the same number.')
]},
'logic':{summary:'Experiment with gates and distinguish OR from XOR, and Boolean addition from arithmetic addition.',takeaway:'OR means at least one input is 1; two-input XOR means the inputs differ.',sections:[
e('Binary and Boolean values','Digital logic usually represents states with 0 and 1. Boolean algebra defines operations on these values. The + symbol means OR, multiplication or juxtaposition means AND, and a bar or apostrophe means NOT. Therefore, Boolean 1 + 1 = 1, not 2.'),
e('The gate family','AND outputs 1 when every input is 1. OR outputs 1 when at least one input is 1. Two-input XOR outputs 1 when the inputs differ. NOT inverts one input. NAND, NOR, and XNOR negate AND, OR, and XOR, respectively.'),
e('Truth tables','A truth table lists every possible input combination. For n independent inputs, it has 2^n rows. F = x + y′z has three inputs and therefore eight rows. Compute y′ first, AND it with z, then OR the result with x.'),
e('Useful simplification laws','Identity: A + 0 = A and A·1 = A. Complement: A + A′ = 1 and A·A′ = 0. Idempotence: A + A = A. De Morgan: (A·B)′ = A′ + B′, and (A+B)′ = A′·B′. Verify a simplification by comparing the original and simplified truth tables.'),
e('Turn an expression into a circuit','F = x + y′z needs a NOT gate on y, an AND gate combining that result with z, and an OR gate combining the AND output with x. Changing the connections can change the function: (x+y′)z is a different expression. Check parentheses and truth tables when unsure.')
]},
'circuits':{summary:'Addition, selection, and storage: understand half-adders, full-adders, multiplexers, and flip-flops.',takeaway:'Combinational circuits compute from current inputs; sequential circuits also retain state.',sections:[
e('Combinational vs. sequential','After propagation delay, a combinational circuit’s output depends on its current inputs. A sequential circuit also depends on stored state. Adders and multiplexers are combinational; flip-flops and registers are sequential. Stored state is the key distinction.'),
e('Half-adder','A half-adder adds bits A and B. It produces two output bits because binary 1+1 = 10. Sum = A XOR B and Carry = A AND B. It has no carry-in, so it cannot by itself add a column that receives a carry from a lower column.'),
e('Full-adder','A full-adder takes A, B, and carry-in. Sum = A XOR B XOR Cin, and Cout = AB + ACin + BCin. Connecting full-adders lets each column pass a carry to the next higher column. With A = B = Cin = 1, Sum = 1 and Cout = 1: binary 11, or decimal 3.'),
e('Encoders and decoders','A decoder turns n input bits into a selection among up to 2^n outputs. An encoder represents a selected input with a binary code. A basic encoder generally assumes one active input; a priority encoder handles multiple active inputs according to a defined priority.'),
e('A 4-to-1 MUX','A multiplexer selects one of four inputs using two selector bits. S1S0 = 00 selects I0, 01 selects I1, 10 selects I2, and 11 selects I3. It forwards the selected input value; it does not add all input values.'),
e('D flip-flops and registers','A D flip-flop stores one bit and updates Q at the appropriate clock edge for its design. Between edges, it retains state. A 64-bit register can be implemented using 64 flip-flops. A clock signal alone does not make a circuit sequential; stored state and its update mechanism matter.')
]},
'assembly-basics':{summary:'Understand the parts of an assembly file before memorizing instruction names.',takeaway:'Instructions execute operations; directives guide the assembler; labels identify locations.',sections:[
e('What is RISC-V?','RISC-V is an open, modular instruction set architecture, not a single processor model. Development began at UC Berkeley in 2010. A base ISA provides a foundation, with optional extensions such as M for integer multiplication and division. RV64 means XLEN = 64: the integer register width.'),
e('Four parts of an assembly file','Comments explain code, labels name locations, instructions specify operations, and directives guide the assembler. A label ends with a colon; a directive usually starts with a dot. .word 10 defines a 32-bit data value; it is not an ALU instruction.'),
e('Types of operand','An operand can be a register such as x10 or its alias a0, an immediate such as 7, or a symbol such as compute. The assembler and linker resolve symbols and addresses. Arithmetic instructions such as add usually place the destination before the two source operands.'),
e('Pseudo-instructions','mv, li, j, beqz, and nop are convenient names that can expand into base instructions. mv a2,a0 is equivalent to addi a2,a0,0, and nop to addi x0,x0,0. A large li value may require several instructions, so source-line count does not always equal instruction count.'),
e('Reading the a^b example','Save the original a in a2 and initialize the result a0 to 1. While a1 is nonzero, multiply the accumulator by a2, decrement the counter, and repeat. For b = 0, the result remains 1. The example assumes a nonnegative integer exponent and multiplication support such as M. Large results may wrap at the register width.'),
e('A teaching example vs. a complete function','The lab template ends with nop for illustration. nop does not return to the caller. A callable function needs the ABI conventions and a return instruction such as ret. Here, the goal is to trace the example, rather than treat the template as a complete operating-system program.')
]},
'performance':{summary:'Clock rate alone is insufficient. Combine instruction count, CPI, and frequency to calculate execution time.',takeaway:'Compare CPU time for the same task, then divide the slower time by the faster time.',sections:[
e('Performance is the inverse of time','For a fixed task, Performance = 1 / Execution Time. If A finishes in 10 s and B in 15 s, A is 1.5× faster because PerformanceA / PerformanceB = TimeB / TimeA. Keep the ratio direction clear: less execution time means more performance.'),
e('Clock period and clock rate','Clock period is the duration of one cycle. Clock rate is the number of cycles per second, so T = 1/f. At 4 GHz, the cycle time is 0.25 ns = 250 ps. GHz = 10^9 Hz, ns = 10^-9 s, and ps = 10^-12 s.'),
e('The CPU time equation','Cycles = Instruction Count × Average CPI. CPU time = Cycles × Clock period = IC × CPI / Clock rate. Use dynamic IC: the instructions actually executed, including repeated loop iterations. CPU time is different from elapsed time, which can also include I/O waiting and other system activity.'),
e('Lab02 example: two computers','A executes 1,000,000 instructions with CPI = 2 at 2 GHz: 2,000,000 cycles and 1 ms. B executes 800,000 instructions with CPI = 3 at 2.5 GHz: 2,400,000 cycles and 0.96 ms. Despite its higher CPI, B is faster by 1/0.96 ≈ 1.0417×. A 4% time reduction corresponds to about 4.17% more performance.'),
e('A cycle-time example','A has a 250 ps clock period and CPI = 2, averaging 500 ps per instruction. B has a 500 ps period and CPI = 1.2, averaging 600 ps per instruction. For one million instructions, A takes 0.5 ms and B takes 0.6 ms. A is 1.2× faster; B’s lower CPI does not compensate for its longer clock period.'),
e('Compiler optimization','If IC decreases by 20%, average CPI increases by 15%, and frequency stays constant, Tnew/Told = 0.8×1.15 = 0.92. Execution time decreases by 8%, while performance increases by 1/0.92−1 ≈ 8.70%. Multiply the factors instead of adding the percentages.')
]},
'cpi-mix':{summary:'Average CPI is weighted by the number of instructions in each class.',takeaway:'More instructions can still execute faster if they require fewer total cycles.',sections:[
e('Instruction classes','If classes A, B, and C have CPI values 1, 2, and 3, their simple average is valid only when their instruction counts are equal. Calculate total cycles first, or weight each CPI by its share of the instruction mix.'),
e('Lecture sequence 1','A = 2, B = 1, C = 2, so IC = 5. Cycles = 2×1 + 1×2 + 2×3 = 10. Average CPI = 10/5 = 2. The sequence contains five executed instructions but needs ten cycles in this model.'),
e('Lecture sequence 2','A = 4, B = 1, C = 1, so IC = 6. Cycles = 4×1 + 1×2 + 1×3 = 9. Average CPI = 9/6 = 1.5. At the same clock period, sequence 2 is faster despite having more instructions.'),
e('An instruction mix given as percentages','For 50% class A at CPI = 1, 30% class B at CPI = 2, and 20% class C at CPI = 4, Average CPI = 0.5×1 + 0.3×2 + 0.2×4 = 1.9. The instruction-mix percentages must total 100%.'),
e('The factors are connected','The algorithm, language, compiler, and ISA influence IC and the instruction mix. Microarchitecture influences execution cost and clock rate. Changing one factor can change another, so return to the CPU time equation for each comparison.')
]},
'registers':{summary:'There are 32 integer registers, with numerical names, ABI aliases, and agreed calling-convention roles.',takeaway:'Aliases name the same registers. RV64 specifies data width, not the length of every instruction.',sections:[
e('RV64 and RV32','RV64I has 32 integer registers, x0 through x31, each 64 bits wide. RV32I has the same number of registers with a 32-bit width. Register width differs from instruction length: base instructions remain 32 bits long. The ld and sd examples here use RV64.'),
e('The special x0 register','Reading x0 always gives zero; writes to x0 are discarded. Therefore, add x5,x6,x0 copies x6, and sub x5,x0,x6 computes the negative of x6. This simplifies common operations without reserving a writable register that must be initialized to zero.'),
e('ABI aliases','x10 and a0 name the same register. The ABI defines conventions between programs and functions: where arguments and return values go, and who preserves register values across a function call.',{table:{heads:['Registers','Aliases','Role'],rows:[['x0','zero','Constant zero'],['x1','ra','Return address'],['x2','sp','Stack pointer'],['x3 / x4','gp / tp','Global / Thread pointer'],['x5–x7','t0–t2','Temporaries'],['x8 / x9','s0(fp) / s1','Saved; x8 may be the frame pointer'],['x10–x17','a0–a7','Arguments; a0/a1 also carry applicable return values'],['x18–x27','s2–s11','Saved registers'],['x28–x31','t3–t6','Temporaries']]}}),
e('The complete saved-register group','x8 is s0 and may serve as fp; x9 is s1; x18–x27 are s2–s11. Together, they form 12 saved registers. x9 plus x18–x27 alone is only 11 registers. A frame pointer is optional under the relevant ABI conventions.'),
e('Registers vs. memory','Registers are small and fast, but limited in number. The compiler tries to keep frequently used values in them; insufficient registers can cause register spilling to memory. The 200× and 10,000× comparisons in the lecture are historical examples, not fixed guarantees for all hardware.'),
e('Smaller is faster','More registers can mean larger circuits, longer signal paths, and more complex access. This is a design principle rather than a ban on larger designs. Choosing a register count balances hardware performance against software register-allocation pressure.')
]},
'arithmetic':{summary:'Break a large expression into small operations and store intermediate results in temporary registers.',takeaway:'Check operand order, split the calculation, and use addi for small signed constants.',sections:[
e('Three operands','add rd,rs1,rs2 means rd = rs1 + rs2; sub rd,rs1,rs2 means rd = rs1 − rs2. The destination is first. Source operands are registers, so add does not directly add two RAM locations. Sources are read before the destination is written, making add x5,x5,x6 valid.'),
e('The lecture expression','Let f be in x19 and g, h, i, j in x20, x21, x22, x23. To evaluate f = (g+h) − (i+j), compute the two additions in x5 and x6, then subtract. For g = 8, h = 4, i = 3, and j = 2, the result is 7.'),
e('An immediate is encoded in the instruction','addi x22,x22,4 adds 4 without loading a constant from memory. Its immediate is signed and 12 bits wide, ranging from −2048 to +2047. Lecture 2, page 32, shows an 11-bit range of −1024..1023; this is a slide error relative to the official ISA.',{note:'Documented correction: addi uses a signed 12-bit immediate, as specified by the RISC-V ISA.'}),
e('Why is there no subi here?','addi accepts a negative immediate, so addi x5,x5,-7 subtracts 7. The constant is encoded in the instruction. If a constant does not fit, the assembler or compiler uses an appropriate sequence; a li pseudo-instruction may expand into multiple instructions.'),
e('Simplicity favors regularity','Regular instruction formats help simplify decoding hardware. “Make the common case fast” motivates efficient support for frequent operations such as small constants. “All instructions have three operands” is too broad: it describes these arithmetic examples, while nop, ret, and other instructions differ.'),
e('Results have a limited width','RISC-V integer add/sub do not automatically trap on arithmetic overflow; results are retained within XLEN bits. The interactive example uses 64-bit values to preserve RV64 behavior. Programs that need overflow detection can implement suitable checks.')
]},
'load-store':{summary:'An array index is different from a byte offset. Multiply the index by the element size in bytes.',takeaway:'Offsets are in bytes. Loads move memory data into registers; stores move register data into memory.',sections:[
e('Byte-addressed memory','Each RISC-V memory address identifies an 8-bit byte. A word is 32 bits, or 4 bytes; a doubleword is 64 bits, or 8 bytes. An RV64 register can hold a doubleword, but loads may access smaller values. The array element type determines the spacing between elements.',{table:{heads:['Type','Bits','Bytes','Load / Store'],rows:[['Byte','8','1','lb / sb'],['Halfword','16','2','lh / sh'],['Word','32','4','lw / sw'],['Doubleword','64','8','ld / sd']]}}),
e('Effective address','Address of A[i] = Base Address + i × Element Size. The offset(rs1) form adds a signed byte offset to the base-register value. If x22 = 4096 and A contains doublewords, A[8] is at 4096 + 8×8 = 4160.'),
e('Load, calculate, then store','To execute A[12] = h + A[8], assume h is in x21, the base is in x22, and elements are 64 bits. ld reads A[8] at offset 64; add computes the result in a register; sd writes it at offset 96. The first sd operand supplies the value to store, rather than naming a destination register.'),
e('Sign extension','In RV64, lb, lh, and lw sign-extend their loaded values to 64 bits. For byte 11111111, lb produces −1; lbu zero-extends it to 255. ld transfers all 64 bits. A smaller store such as sb writes the lowest 8 register bits.'),
e('Natural alignment','A word is naturally aligned when its address is divisible by 4, and a doubleword when divisible by 8. Address 4096 is aligned for ld; 4098 is not. Misaligned access may be supported or may trap depending on the execution environment; it is not universally forbidden.',{note:'Lab02 presents alignment as a simplified rule. The ISA makes misaligned-access behavior dependent on the execution environment.'}),
e('The element type of B in Task01','Lab02 Task01 does not specify the size of B’s elements. For doublewords, use ld/sd with offsets 8 and 24. For words, use lw/sw with offsets 4 and 12. State the assumption explicitly: RV64 does not imply that every array contains 64-bit elements.')
]},
'binary':{summary:'The pattern 1111 can represent 15 or −1. Its interpretation determines its meaning.',takeaway:'Bits alone do not specify signedness. Width and interpretation are part of the value’s meaning.',sections:[
e('Unsigned interpretation','An n-bit unsigned value ranges from 0 to 2^n−1. Every bit has a positive weight: from the right, 1, 2, 4, 8, and so on. For example, 4-bit 1011 means 8+2+1 = 11.'),
e('Two’s complement','For a signed two’s complement value, the highest bit has weight −2^(n−1); the other weights stay positive. In 4 bits, 1100 = −8+4 = −4, and 1111 = −8+4+2+1 = −1. The range is −2^(n−1) to 2^(n−1)−1. There is one extra negative value because zero occupies a nonnegative pattern.'),
e('How to negate a value','Represent +2 in 8 bits as 00000010. Invert the bits to get 11111101, then add 1 to get 11111110, which represents −2. This operates within a fixed width; changing the width requires the appropriate representation.'),
e('The minimum-value case','In signed 4-bit two’s complement, −8 is 1000. Negating it at the same width gives 1000 again because +8 is outside the range. This is overflow. Not every negative value has a representable positive counterpart at the same width.'),
e('Sign extension','To widen a signed value, replicate its sign bit: 4-bit 1100 (−4) becomes 8-bit 11111100. To widen an unsigned value, add leading zeros: unsigned 1100 (12) becomes 00001100. Preserve both the value and its interpretation.'),
e('64-bit limits','The unsigned 64-bit range is 0 to 18,446,744,073,709,551,615. The signed range is −9,223,372,036,854,775,808 to 9,223,372,036,854,775,807. The unsigned number on Lecture 2, page 33, contains a typographical error; 2^64−1 gives the correct maximum.')
]},
'formats':{summary:'Read the R-type fields and distinguish the compiler, assembler, linker, and loader.',takeaway:'Register width differs from instruction length. Each toolchain stage has a separate job.',sections:[
e('Levels of program code','A high-level language expresses the problem. Assembly is a textual representation of ISA instructions. Machine code is the binary encoding understood by the processor. One C statement may produce several instructions, so source-line count does not determine IC.'),
e('R-type fields','add x5,x20,x21 uses opcode, funct3, and funct7 to identify the operation; rd selects the destination; rs1 and rs2 select the sources. A register index needs 5 bits for 32 choices. The R-type field widths total 7+5+5+3+5+7 = 32 bits.'),
e('Format families','R is used for register arithmetic, I for immediates and loads, S for stores, B for branches, U for upper immediates, and J for jumps. Lab02 omits U from its list; it is included here for completeness. B and J arrange their immediates differently, so do not apply the addi range to them.',{table:{heads:['Format','Examples','Main idea'],rows:[['R','add, sub','Two sources and a destination'],['I','addi, ld','A source, immediate, and destination'],['S','sd','An address and a value to store'],['B','beq','Register comparison and branch'],['U','lui, auipc','Upper immediate'],['J','jal','Jump and return address']]}}),
e('32-bit base instructions','Base integer instruction formats are 32 bits long, independently of RV32 or RV64 register width. The C extension adds 16-bit compressed instructions. Therefore, the statement “all RISC-V instructions are 32 bits long” only fits the base-instruction context used here.'),
e('The compilation toolchain','The compiler translates C into assembly. The assembler produces object files containing machine code and relocation information. The linker combines objects and libraries and resolves symbols. The loader places the program in memory for the execution environment. Bare-metal loading can differ by system.',{list:['C source → Compiler → Assembly','Assembly → Assembler → Object file','Objects + libraries → Linker → Executable','Executable → Loader → Memory']}),
e('Trying a simulator','Lab02 suggests CPUlator for assembly and tracing. Check the selected system and supported ISA before copying an example: ld/sd require RV64, and mul requires multiplication support such as M. This site traces three specific teaching examples; use a suitable RV64 tool to run complete programs.')
]},
'lab-tasks':{summary:'Worked MUX, a³, array, and performance exercises, with explicit assumptions and step-by-step reasoning.',takeaway:'A good solution states its assumptions and explains every instruction or calculation.',sections:[
e('Lab01 · Task01 · 4-to-1 MUX','Draw inputs I0..I3 entering the MUX, selectors S1 and S0, and output Y. Selection: 00→I0, 01→I1, 10→I2, 11→I3. If S1S0 = 10 and I2 = 1, then Y = 1 regardless of the other inputs. The Circuits experiment lets you try every combination.'),
e('Lab01 · Task02 · a³','Preserve the original a because a0 changes. A direct solution is mv t0,a0, then mul a0,a0,t0 for a², then mul a0,a0,t0 for a³. It requires multiplication support such as M and retains the lowest XLEN bits if the result overflows.'),
e('Compute a³ with a loop','Following the lab’s a^b pattern, save a in a2, set counter a1 to 3, and initialize the accumulator to 1. Multiply and decrement until the counter reaches zero. Compare this loop’s instruction cost with the direct solution. A callable function needs ret to return; nop here follows the teaching template.'),
e('Lab02 · Task01 · B[3] = B[1] + 7','Assume doubleword elements and base address in x20. The offsets are 8 for B[1] and 24 for B[3]. Load into t0 = x5, add 7 with addi, and store the result. If B[1] = 12, then B[3] = 19. The base register retains the original address.'),
e('Lab02 · Task02 · compare the computers','For one million instructions, A takes 10^6×2×250×10^-12 = 0.0005 s = 0.5 ms. B takes 10^6×1.2×500×10^-12 = 0.0006 s = 0.6 ms. A is faster by 0.6/0.5 = 1.2×. Lower CPI alone does not imply higher performance when the clock period is longer.'),
e('Review your solution','State the inputs and assumptions, especially array element size. Then show the equation, substitute values with units, and explain the result. In assembly, annotate register roles and trace values manually. These are study solutions; follow your instructor’s lab-format requirements.')
]}
};

export const englishGroups={
lect1:{title:'The big picture',desc:'From a program to the components that execute it.'},
lab1:{title:'From logic to assembly',desc:'Gates, circuits, and your first RISC-V program.'},
lect2:{title:'Performance and the computer’s language',desc:'Calculate execution time and understand registers and memory.'},
lab2:{title:'Put the concepts to work',desc:'Instruction formats and worked lab solutions.'}
};
