import {lessons} from './content.js';
let counter=0;
const mc=(lesson,text,options,explanation,difficulty='أساسي')=>({id:++counter,lesson,text,options,correct:0,explanation,difficulty,type:'mcq'});
const wr=(lesson,text,answer,difficulty='تطبيقي')=>({id:++counter,lesson,text,answer,difficulty,type:'written'});
export const questions=[
mc('abstraction','أي وصف يخص Architecture؟',['التعليمات والـRegisters المتاحة للمبرمج','عدد مراحل Pipeline فقط','نوع Transistors فقط','مكان مروحة التبريد'],'ISA تحدد واجهة البرنامج. التنفيذ الداخلي مثل Pipeline جزء من Microarchitecture.'),
mc('abstraction','معالجان ينفّذان نفس ISA لكن CPI مختلف. إيه التفسير؟',['Microarchitecture مختلفة','لا يمكن أن ينفّذا نفس ISA','أسماء Registers مختلفة بالضرورة','البرامج تحتاج لغة مختلفة'],'نفس Instruction semantics ممكن تتنفّذ بتصاميم مختلفة وبالتالي تكلفة مختلفة.'),
mc('abstraction','أي طبقة تدير موارد Memory وI/O للبرامج؟',['Operating System','Logic gate','ALU وحدها','Assembler directive'],'الـOperating System يوفر خدمات لإدارة الموارد والتعامل مع الأجهزة.'),
wr('abstraction','اشرح الفرق بين ISA وMicroarchitecture بمثال add.','ISA تحدد أن add rd,rs1,rs2 تجمع المصدرين وتضع النتيجة في rd. Microarchitecture تحدد دوائر ALU وControl وعدد Cycles وكيف تتداخل التعليمات. نفس ISA لا تضمن نفس الأداء.'),
mc('von-neumann','Stored-program في Von Neumann تعني إيه؟',['تعليمات البرنامج والبيانات مخزنة في Memory','كل تعليمة تحتاج إعادة توصيل الأسلاك','البرنامج مخزن في ALU','Memory لا تحتفظ بتعليمات'],'البرنامج قابل للتخزين والجلب مثل البيانات في النموذج الكلاسيكي.'),
mc('von-neumann','مين ينسق ترتيب العمليات ويرسل Control signals؟',['Control Unit','Output device','Memory cell','Data Bus'],'CU تنسق؛ ALU تحسب؛ Memory تخزن.'),
mc('von-neumann','أي مثال يمكن أن يكون Input وOutput معًا؟',['Network card','Keyboard بسيطة','Printer بسيطة','ALU'],'Network card تستقبل وترسل بيانات.'),
wr('von-neumann','يعني إيه Memory-mapped I/O؟','بعض عناوين فضاء الذاكرة تمثل Device Registers بدل RAM. قراءة أو كتابة العنوان تتعامل مع الجهاز. ده مختلف عن استخدام تعليمات I/O متخصصة.'),
mc('memory-buses','Address Bus من 16 bit مع Byte-addressed memory يتيح كام؟',['64 KiB','16 KiB','64 bit','4 GiB'],'2^16 = 65,536 موقع، وكل موقع Byte؛ السعة 64 KiB.'),
mc('memory-buses','أي Register يحمل القيمة التي تنتقل من أو إلى Memory في النموذج العام؟',['MDR','MAR','PC دائمًا','IR دائمًا'],'MDR للـData وMAR للـAddress.'),
mc('memory-buses','شريحة 4M × 16-bit، مع M=2^20، سعتها كام؟',['8 MiB','4 MiB','64 MiB','16 MiB'],'2^22 موقع ×16 bit =2^26 bit =2^23 bytes=8 MiB.','تطبيقي'),
mc('memory-buses','ذاكرة 1024 موقع تحتاج كام Address bits؟',['10','8','16','1024'],'1024=2^10؛ تحتاج 10 bits لتحديد المواقع.'),
wr('memory-buses','اشرح خطوات كتابة القيمة X في العنوان A باستخدام MAR وMDR.','MDR ← X، ثم MAR ← A، ثم إرسال Write signal؛ الذاكرة تحفظ X في الموقع A. قد تختلف التفاصيل الزمنية حسب التنفيذ، لكن Address وData لهما دور منفصل.'),
mc('cpu-cycle','إيه الفرق الأساسي بين PC وIR؟',['PC عنوان؛ IR محتوى تعليمة','PC بيانات؛ IR عنوان Memory دائمًا','هما نفس Register','IR يحفظ نتائج ALU فقط'],'PC يحدد مكان جلب التعليمة، وIR يحتفظ بالتعليمة في النموذج التعليمي.'),
mc('cpu-cycle','للتنفيذ المتسلسل لتعليمات Base RISC-V 32-bit، PC غالبًا يزيد كام؟',['4 bytes','1 byte','8 bytes دائمًا لأن RV64','32 bytes'],'32-bit = 4 bytes؛ RV64 عرض Register، مش طول التعليمة.'),
mc('cpu-cycle','هل Store/Write-back في الدورة يعني إن كل تعليمة تكتب في RAM؟',['لا؛ قد يكتب الناتج في Register','نعم؛ حتى add تحتاج sd ضمنيًا','نعم؛ كل Registers داخل RAM','لا توجد أي كتابة نهائيًا'],'add تحدث Destination Register؛ Store instruction فقط تكتب بيانات إلى Memory.'),
mc('cpu-cycle','هل Base RISC-V arithmetic تعتمد على Zero/Carry flags عامة مثل بعض ISAs؟',['لا؛ لا توجد Condition-code flags بهذه الصورة','نعم؛ كل add تضبط Flags إلزاميًا','نعم؛ x0 هو Flags Register','نعم؛ MAR يحمل Flags'],'مخطط Flags في المحاضرة عام. RISC-V branches تقارن Registers مباشرة.','تطبيقي'),
mc('evolution','لو 20% من المهمة Serial، الحد الأقصى المثالي للـSpeedup كام؟',['5×','20×','بلا حد','0.2×'],'عند عدد Cores غير محدود، الحد =1/0.2=5.','تطبيقي'),
mc('evolution','20% Serial على 4 Cores، Speedup المثالي؟',['2.5×','4×','5×','1.25×'],'1/(0.2+0.8/4)=1/0.4=2.5.','تطبيقي'),
mc('evolution','Moore’s Law مرتبطة أساسًا بإيه؟',['اتجاه نمو عدد وكثافة Transistors','مضاعفة أداء كل برنامج بالضرورة','قانون لتنفيذ add','زيادة CPI مع الوقت'],'عدد Transistors والأداء والطاقة مفاهيم مختلفة.'),
wr('evolution','برنامج 100s، منه 30% Serial، على 8 Cores. احسب الزمن المثالي والـSpeedup.','Tnew = 30 + 70/8 = 38.75s. Speedup =100/38.75≈2.5806×. الحد الأقصى =1/0.3≈3.3333×. نفترض عدم وجود overhead وحجم مهمة ثابت.','متقدم'),
mc('logic','متى XOR ذات مدخلين تخرج 1؟',['عندما يختلف المدخلان','عندما يكون الاثنان 1 فقط','في كل الحالات','عندما يتساوى المدخلان'],'XOR مختلفة عن OR؛ الحالة 11 تعطي XOR=0 وOR=1.'),
mc('logic','في Boolean Algebra، 1 + 1 تساوي كام؟',['1','2','10','غير معرّفة'],'+ هنا OR، وليس جمعًا حسابيًا.'),
mc('logic','دالة Boolean فيها 3 Inputs مستقلة تحتاج كام صف في Truth Table؟',['8','3','6','9'],'عدد الاحتمالات 2^3=8.'),
mc('logic','F=x+y′z عند x=0 وy=0 وz=1 تساوي؟',['1','0','2','لا يمكن تحديدها'],'y′=1، ثم y′z=1، ثم x OR 1=1.','تطبيقي'),
mc('logic','أي تعبير يساوي NOT(A AND B)؟',['(NOT A) OR (NOT B)','(NOT A) AND (NOT B)','A OR B','A XOR B'],'قانون De Morgan: نفي AND يصبح OR بين النفيين.','تطبيقي'),
wr('logic','ارسم بوصف نصي دائرة F=x+y′z.','y تمر على NOT؛ الناتج يدخل AND مع z؛ خرج AND يدخل OR مع x؛ خرج OR هو F. الترتيب يمثل x OR ((NOT y) AND z).'),
mc('circuits','أي دائرة Sequential؟',['D Flip-Flop','MUX','Half-Adder','Decoder'],'D Flip-Flop يحتفظ بState؛ الدوائر الأخرى المذكورة Combinational.'),
mc('circuits','Half-Adder عند A=B=1 يعطي إيه؟',['Sum=0, Carry=1','Sum=1, Carry=0','Sum=1, Carry=1','Sum=0, Carry=0'],'1+1=10 binary؛ Sum أدنى bit وCarry أعلى bit.'),
mc('circuits','MUX 4×1 يحتاج كام Selector bits؟',['2','4','1','8'],'2^2=4 اختيارات.'),
mc('circuits','S1S0=10 في MUX 4×1 يختار مين؟',['I2','I0','I1','I3'],'10 binary=2؛ تُختار I2.'),
mc('circuits','Full-Adder عند A=B=Cin=1 يعطي إيه؟',['Sum=1, Cout=1','Sum=0, Cout=1','Sum=1, Cout=0','Sum=0, Cout=0'],'1+1+1=3=11 binary.','تطبيقي'),
wr('circuits','اكتب معادلة خرج MUX 4×1.','Y = S1′S0′I0 + S1′S0I1 + S1S0′I2 + S1S0I3. كل term يُفعّل Input واحدة حسب Selector bits، وجمع الـterms هو OR.'),
mc('assembly-basics','أي سطر Directive؟',['.word 10','add x5,x6,x7','compute:','mul a0,a0,a2'],'النقطة تبدأ Directive لتوجيه Assembler، هنا تعريف بيانات 32-bit.'),
mc('assembly-basics','mv a2,a0 تساوي أي Base instruction؟',['addi a2,a0,0','add a0,a2,a2','sd a2,0(a0)','sub a2,x0,a0'],'إضافة صفر تنسخ القيمة إلى a2.'),
mc('assembly-basics','mul تتطلب أي Extension؟',['M','C بالضرورة','فقط RV64I الأساسية','لا يمكن تنفيذها في RISC-V'],'M extension تحتوي integer multiplication/division؛ RV64I وحدها لا تضمن mul.'),
mc('assembly-basics','مثال pow يبدأ accumulator=1. الناتج عند b=0؟',['1','0','a','a²'],'الفرع يخرج قبل أي ضرب، فيبقى الناتج 1 ضمن افتراضات المثال.'),
mc('assembly-basics','هل nop في نهاية قالب اللاب تعني Return للـCaller؟',['لا؛ nop لا تقوم بالعودة','نعم؛ nop مرادف ret','نعم؛ تصفر PC','نعم؛ تحفظ ra في Memory'],'nop لا تنفذ تغييرًا مفيدًا؛ Function تحتاج Return مناسبة.','تطبيقي'),
wr('assembly-basics','صنّف: # comment، loop:، addi a0,a0,1، .dword 5.','بالترتيب: Comment، Label، Instruction، Directive. Comments تُتجاهل، Labels تمثل مواقع، Instructions تترجم إلى Machine code، وDirectives توجه عملية التجميع.'),
mc('performance','A تستغرق 10s وB تستغرق 15s. A أسرع بمعامل؟',['1.5×','0.667×','5×','2.5×'],'PerformanceA/PerformanceB=TimeB/TimeA=15/10.'),
mc('performance','Clock rate = 4 GHz. Clock period؟',['250 ps','4 ns','4 ps','250 ns'],'1/(4×10^9)=0.25ns=250ps.','تطبيقي'),
mc('performance','IC=10^6، CPI=2، Clock=2GHz. CPU time؟',['1 ms','1 s','2 ms','0.5 ms'],'10^6×2/(2×10^9)=0.001s.','تطبيقي'),
mc('performance','IC يقل 20% وCPI يزيد 15% مع تردد ثابت. ماذا يحدث للزمن؟',['يقل 8%','يقل 5%','يزيد 35%','يقل 20%'],'النسبة 0.8×1.15=0.92؛ الزمن أقل 8%.','تطبيقي'),
mc('performance','A=1ms وB=0.96ms لنفس المهمة. أيهما أسرع؟',['B بمعامل 1.0417× تقريبًا','A بمعامل 1.0417×','B بمعامل 4×','متساويان'],'1/0.96≈1.0417؛ الزمن الأقل أفضل.','تطبيقي'),
wr('performance','حل Lab02 Task02: مليون Instruction؛ A=250ps وCPI2، B=500ps وCPI1.2.','A: 10^6×2×250×10^-12=0.5ms. B:10^6×1.2×500×10^-12=0.6ms. A أسرع بمعامل 0.6/0.5=1.2×.'),
wr('performance','لو الزمن قل 8%، احسب نسبة زيادة Performance.','Tnew=0.92Told؛ Pnew/Pold=1/0.92≈1.0869565. الزيادة≈8.70%. خفض الزمن وزيادة الأداء ليستا نفس النسبة.','متقدم'),
mc('cpi-mix','A,B,C أعدادها 2,1,2 وCPI=1,2,3. Average CPI؟',['2','1.5','3','1'],'Cycles=2+2+6=10؛ IC=5؛ المتوسط=2.','تطبيقي'),
mc('cpi-mix','أعداد 4,1,1 وCPI=1,2,3 تعطي كام Cycle؟',['9','6','10','12'],'4×1+1×2+1×3=9.','تطبيقي'),
mc('cpi-mix','برنامج 50% CPI1 و30% CPI2 و20% CPI4. Average CPI؟',['1.9','2.333','7','1.5'],'0.5×1+0.3×2+0.2×4=1.9.','تطبيقي'),
wr('cpi-mix','لماذا Sequence فيها 6 Instructions ممكن تكون أسرع من أخرى فيها 5؟','لو Cycles الأولى 9 والثانية 10، عند نفس Clock period زمن الأولى أقل. IC وحده لا يكفي؛ حاصل IC×Average CPI هو عدد Cycles.'),
mc('registers','x10 وa0 يشيران لإيه؟',['نفس Register','Registerين مختلفين','عنوان Memory واحد فقط','Instruction واحدة'],'a0 هو ABI alias لـx10.'),
mc('registers','الكتابة في x0 تعمل إيه؟',['تُتجاهل ويظل صفرًا','تغيّر قيمة x0','تغيّر PC','تسبب overflow دائمًا'],'x0 hardwired to zero؛ الكتابة لا تغيّر القيمة.'),
mc('registers','RV64I فيها كام Integer Register، وما عرضها؟',['32، كل واحد 64 bit','64، كل واحد 32 bit','32، كل واحد 32 bit','64، كل واحد 64 bit'],'RV64I لها x0..x31 وXLEN=64.'),
mc('registers','أي Register هو sp في ABI؟',['x2','x1','x8','x10'],'x1=ra، x2=sp، x8=s0 ويمكن fp، x10=a0.'),
wr('registers','اذكر مجموعة Saved Registers كاملة.','x8=s0 (قد يُستخدم fp)، x9=s1، x18..x27=s2..s11. المجموع 12؛ كلها callee-saved في ABI المعتاد.'),
mc('arithmetic','sub x5,x6,x7 تعني إيه؟',['x5 = x6 − x7','x7 = x5 − x6','x5 = x7 − x6','x6 = x5 − x7'],'Destination أول Operand، وترتيب الطرح مهم.'),
mc('arithmetic','مدى Immediate في addi؟',['−2048 إلى 2047','−1024 إلى 1023','0 إلى 4095 فقط','−32768 إلى 32767'],'Immediate signed 12-bit وفق المواصفة. الرقم في Lect2 p32 يحتاج تصحيحًا.'),
mc('arithmetic','إزاي تطرح Constant=7 من x5؟',['addi x5,x5,-7','subi x5,x5,7','addi x5,x5,7','sub x5,x5,7'],'addi تقبل Constant سالبة، وsub تتوقع Register كـOperand ثالث في هذه الصيغة.'),
wr('arithmetic','ترجم f=(g+h)−(i+j)؛ f=x19 وg..j في x20..x23.','add x5,x20,x21\nadd x6,x22,x23\nsub x19,x5,x6\nالجمعان مستقلان؛ x5 وx6 يحفظان intermediate results قبل الطرح.'),
mc('load-store','A عناصرها Doublewords. Offset A[8] كام؟',['64 bytes','8 bytes','32 bytes','512 bytes'],'8×8 bytes=64.'),
mc('load-store','أي وصف صحيح لـsd x9,96(x22)؟',['يحفظ قيمة x9 في Memory عند x22+96','يقرأ Memory إلى x9','يضع 96 في x22','يجمع x9 وx22'],'sd Store؛ x9 مصدر البيانات، وx22 Base address.'),
mc('load-store','lw في RV64 تقرأ 0xFFFFFFFF. النتيجة Signed؟',['−1','4,294,967,295','0','255'],'lw تعمل Sign-extension من 32 إلى64 bits. lwu تعطي القيمة Unsigned.','تطبيقي'),
mc('load-store','Base=4096، Word array، Index=3. العنوان؟',['4108','4120','4099','4192'],'Word=4 bytes؛ 4096+3×4=4108.','تطبيقي'),
mc('load-store','بالنسبة لـld، أي عنوان Naturally aligned؟',['4096','4098','4100','4102'],'Doubleword=8 bytes؛ 4096 يقبل القسمة على8.'),
wr('load-store','ترجم B[3]=B[1]+7 والـBase في x20. اذكر الافتراض.','Doubleword elements: ld x5,8(x20) ثم addi x5,x5,7 ثم sd x5,24(x20). لو Word elements: lw x5,4(x20)، addi نفسها، ثم sw x5,12(x20). لا يحدد Task نوع B، لذلك يجب ذكره.'),
mc('binary','1111 في 4-bit Two’s complement تعني؟',['−1','15','−7','7'],'−8+4+2+1=−1.'),
mc('binary','مدى 8-bit Signed Two’s complement؟',['−128..127','−127..128','0..255','−256..255'],'−2^7 إلى2^7−1.'),
mc('binary','نفي +2 على 8 bits يعطي؟',['11111110','11111101','10000010','00000010'],'Invert 00000010 إلى11111101 ثم +1=11111110.'),
mc('binary','1100 على 4 bits كـUnsigned وSigned بالتتابع؟',['12 و−4','−4 و12','12 و4','4 و−12'],'Unsigned=8+4=12؛ Signed=−8+4=−4.'),
mc('binary','Sign-extension لـ4-bit 1100 إلى8 bits؟',['11111100','00001100','11000000','00000100'],'كرر Sign bit=1 للحفاظ على−4.','تطبيقي'),
wr('binary','لماذا نفي −8 على 4 bits لا يعطي +8؟','4-bit Signed range −8..7. +8 غير قابلة للتمثيل. Invert 1000→0111 ثم +1→1000؛ حصل Overflow، وتظل الـBits تمثل −8 على نفس العرض.','متقدم'),
mc('formats','عدد bits لحقل Register يختار من32 Register؟',['5','6','32','64'],'2^5=32.'),
mc('formats','أي Format تستخدمه sd؟',['S-type','R-type','J-type','U-type'],'Store تستخدم S-type وتقسم Immediate على حقلين.'),
mc('formats','أي مرحلة تحوّل Assembly إلى Object/Machine code؟',['Assembler','Compiler من C','Loader','ALU'],'Compiler ينتج Assembly، Assembler يجمعها، Linker يربط، Loader يحمل.'),
mc('formats','هل RV64 تعني أن كل Base Instruction طولها64 bit؟',['لا؛ Base Instructions طولها32 bit','نعم؛ كلها64 bit','نعم؛ ld فقط128 bit','لا؛ كلها8 bit'],'XLEN عرض Integer Register، مختلف عن Instruction encoding length.'),
wr('formats','رتّب مراحل Toolchain واذكر دور Linker.','C → Compiler → Assembly → Assembler → Object files → Linker → Executable → Loader → Memory. Linker يربط Objects وLibraries ويحل الرموز والـRelocations.'),
mc('lab-tasks','في a³، ليه نحفظ a الأصلية في Register مؤقتة؟',['لأن a0 يتغير أثناء حساب a² ثم a³','لأن كل mul تصفر كل Registers','لأن a0 ممنوع استخدامها','لأن Memory لا تخزن أعدادًا'],'لو فقدت a الأصلية، ضرب a² في نفسها يعطي a⁴ بدل a³.'),
mc('lab-tasks','B[1]=12، ثم B[3]=B[1]+7. B[3] تصبح؟',['19','12','84','7'],'Load القيمة12، addi تضيف7، Store الناتج19.'),
wr('lab-tasks','اكتب حل a³ بثلاث تعليمات باستخدام a0 وt0.','mv t0,a0\nmul a0,a0,t0\nmul a0,a0,t0\nنفترض دعم M extension. الأولى تحفظ a، الثانية تعطي a²، والثالثة a³. mv pseudo-instruction هنا تتحول إلى addi بقيمة0.'),
wr('lab-tasks','الـLoop في pow مع a=2 وb=3: تتبع accumulator والعداد بعد كل iteration.','ابدأ accumulator=1 والعداد3. بعد الأولى: 2 والعداد2. الثانية:4 والعداد1. الثالثة:8 والعداد0. beqz تخرج في الاختبار التالي. الناتج8.')
];
for(const q of questions){const l=lessons.find(l=>l.id===q.lesson);q.group=l.group;q.source=l.source;}
